import {
  ArrowDownWideNarrow,
  ArrowLeftRight,
  Binary,
  Blocks,
  Boxes,
  CalendarRange,
  Crosshair,
  Gauge,
  GitBranch,
  GitCompare,
  Grid3x3,
  Hash,
  Layers,
  List,
  Link,
  Network,
  PanelsTopLeft,
  PencilRuler,
  PieChart,
  Share2,
  Sigma,
  TrendingUp,
  Type,
  type LucideIcon,
} from "lucide-react";

/** Resolves the lucide icon referenced by a topic's `icon` field. */
export const HANDBOOK_ICONS: Record<string, LucideIcon> = {
  ArrowDownWideNarrow,
  ArrowLeftRight,
  Crosshair,
  PanelsTopLeft,
  Layers,
  List,
  Gauge,
  Boxes,
  Network,
  Share2,
  Grid3x3,
  Sigma,
  Type,
  Binary,
  Blocks,
  CalendarRange,
  GitBranch,
  GitCompare,
  Hash,
  Link,
  PieChart,
  PencilRuler,
  TrendingUp,
};

export function resolveHandbookIcon(name: string): LucideIcon {
  return HANDBOOK_ICONS[name] ?? Boxes;
}
