/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/env.d.ts --include-runtime false` (hash: 87893392e69c9351e11172a9dda00726)
interface __BaseEnv_Env {
	LC_RATING_DATA: KVNamespace;
	ALLOWED_ORIGINS: "https://youyun8.github.io,http://localhost:3001";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
