import type { TutorialData } from "@/types";

export const interviewSprint = {
  id: 1,
  title: "面試衝刺計畫（2.5 週優先題單）",
  description:
    "以 18 天為週期，聚焦 45 分鐘 coding phone screen 最常考的 9 類題型；用 60 題核心題建立可口述、可實作、可在限時內完成的 C++ 解題模板。",
  src: "",
  last_update: "2026-06-14T00:00:00.000Z",
  summary:
    "這份計畫適合距離 **45 分鐘 coding phone screen（C++）** 約 2–3 週、已有演算法基礎但需要快速收斂複習範圍的人。它從本站 15 章、4166 題中挑出 **60 題核心題**，用 18 天建立九類高頻模板，另補上 **45 題近年加練題**，並預留 2 次模擬面試與 1 天純複習。\n\n**完成標準**：不只把題目 AC，而是能在 5 分鐘內辨識題型並說明解法，約 25 分鐘內完成可執行的 C++，並主動交代複雜度、邊界條件與測試案例。\n\n**優先級評分公式**：`priority = 3I + 2F + L`，三軸各 1–5 分。\n\n| 軸 | 權重 | 意義 |\n| --- | --- | --- |\n| **I — 面試題型權重** | ×3 | 是否屬於核心面試題型（搜尋、DP、圖/網格、區間、資料結構設計、滑動視窗、解析、模擬）；冷門數論或 contest 專屬技巧分數低 |\n| **F — 真實出題頻率** | ×2 | 此「題型」（非原題）近兩年在大廠 phone screen 的出現頻率 |\n| **L — 學習槓桿** | ×1 | 解掉它能否解鎖一整族題（模板題）vs. 一次性技巧 |\n\n**建議使用方式**：先依「18 天衝刺排程」安排每日節奏，再從「高優題單」依章內順序限時練習。每題完成後記錄辨識線索、卡住原因與可複用模板；D-2 不做新題，只重寫錯題並口述解法。",
  children: [
    {
      id: 2,
      title: "1. 18 天衝刺排程",
      description:
        "把 60 題拆成 15 天新題、1 天總複習與 2 次模擬面試；每天都有明確題量、模板目標與驗收方式。",
      summary:
        "排程以面試日前一天為 **D-1** 倒推，將新題、複習與模擬面試分開安排。預設投入量為 **平日 2 小時（3–4 題）、週末 4 小時（5 題）**；請把 5 題的日子（D-15、D-13、D-4）對齊週末，若面試日期不同則整體平移。\n\n每天結束前，至少要能口述當日模板的適用訊號、核心不變式、複雜度與一個常見邊界。**D-3 與 D-1 是混合題型模擬，D-2 只複習不做新題。**\n\n| Day | Date offset | Chapter(s) | # problems | Focus / template to internalize | Mock interview? |\n| --- | --- | --- | --- | --- | --- |\n| 1 | D-18 | 滑動視窗 | 4 | 不定長視窗模板：越長越合法求最短、越短越合法求最長 | – |\n| 2 | D-17 | 滑動視窗 ＋ 二分搜尋 | 4 | 恰好型＝兩次越短型相減；`check(x)` 單調性證明 | – |\n| 3 | D-16 | 二分搜尋 | 4 | 旋轉陣列邊界判斷、最小化最大值（答案二分） | – |\n| 4 | D-15 | 單調堆疊/單調佇列 | 5 | next-greater 模板、左右邊界貢獻法、deque 維護最值 | – |\n| 5 | D-14 | 資料結構 I | 4 | 字首和＋雜湊表計數、堆疊鄰項消除 | – |\n| 6 | D-13 | 資料結構 II | 5 | 堆模板（合併 K 路、會議室）、對頂堆、DSU、Trie | – |\n| 7 | D-12 | 網格圖 I | 3 | flood fill、多源 BFS（全部源點先入隊） | – |\n| 8 | D-11 | 網格圖 II | 3 | 帶狀態 BFS（visited 升維）、0-1 BFS（deque 前後門） | – |\n| 9 | D-10 | 圖論 I | 3 | 拓撲排序（入度法）＋ 環檢測、連通分量 | – |\n| 10 | D-9 | 圖論 II | 4 | 隱式圖建模 BFS、Dijkstra 堆模板（含 K 步限制變形） | – |\n| 11 | D-8 | 動態規劃 I | 4 | 線性 DP（打家劫舍/LIS）、0-1 與完全背包 | – |\n| 12 | D-7 | 動態規劃 II | 4 | LCS/編輯距離雙序列模板、劃分型 DP、網格 DP | – |\n| 13 | D-6 | 動態規劃 III ＋ 樹 I | 4 | 狀態機 DP、帶權區間排程（排序＋二分前驅）；LCA、直徑 | – |\n| 14 | D-5 | 樹 II | 4 | 自底向上 DFS 回傳值設計、BST 中序性質 | – |\n| 15 | D-4 | 貪心與區間 | 5 | 排序＋一次掃描、區間覆蓋的「最遠可達」貪心 | – |\n| 16 | D-3 | 混合模擬 | （2 題模擬） | 45 分鐘限時 mock ×1：建議抽 1129 顏色交替的最短路徑 ＋ 2406 將區間分為最少組數；之後檢討 | ✅ Mock 1 |\n| 17 | D-2 | 全部複習 | 0 | 不做新題：重寫錯題本所有模板、對每章口述「何時用、複雜度、邊界」 | – |\n| 18 | D-1 | 混合模擬 | （2 題模擬） | 45 分鐘限時 mock ×1：建議抽 1631 最小體力消耗路徑 ＋ 1024 影片拼接；只輕量複習，早睡 | ✅ Mock 2 |\n\n合計新題 60 題（D-18 至 D-4）。兩次模擬使用 4 題附錄題，不佔 60 題額度；模擬後請記錄溝通、建模、實作與測試四個階段各自的失分原因。",
    },
    {
      id: 3,
      title: "2. 高優題單",
      description:
        "依 coding phone screen 投報率排序的 60 題核心清單，並為每個主題補上 5 題近年 LeetCode 加練；先掌握高槓桿模板，再用代表變形檢查能否獨立辨識與實作。",
      summary:
        "這份題單將 **60 題核心題** 分成 9 個高頻主題，每章末再加入 5 題近年 LeetCode 加練，合計 **105 題**。章內依 Rating 由低到高排序，無分數者置前；`Score = 3I + 2F + L` 保留作為優先級參考。前段多為可複用的根模板，後段與加練題用來檢查是否能將同一觀念遷移到變形題。\n\n建議章內由上往下練習：每題先限時獨立作答，再記錄「辨識訊號、核心狀態或不變式、易錯邊界」。Rating 欄取自站內資料；無分數者以 `–` 表示。",
      children: [
        {
          id: 31,
          title: "2.1 滑動視窗（11 題）",
          description:
            "練會求最短、求最長與恰好 K 三類不定長視窗；目標是能從限制條件判斷左右端點的移動時機。",
          summary:
            "滑動視窗是 coding phone screen 最常見的陣列與字串題型之一。練習重點不是背迴圈，而是先判斷合法性隨視窗變長或變短的方向，再決定何時移動左端點；計數題則要能說明固定右端點時新增了多少答案。\n\n完成本節後，應能快速區分「越長越合法求最短」、「越短越合法求最長」與「恰好 K＝至多 K−至多 K-1」三類模板。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 3 | [無重複字元的最長子串](https://leetcode.cn/problems/longest-substring-without-repeating-characters/) | sliding_window → 越短越合法/求最長 | – | 5 | 5 | 5 | 30 | 滑動視窗第一模板題，screen 最常見開場題 |\n| 2 | 209 | [長度最小的子陣列](https://leetcode.cn/problems/minimum-size-subarray-sum/) | sliding_window → 越長越合法/求最短 | – | 5 | 5 | 5 | 30 | 「求最短」方向的對偶模板，與 LC 3 成對記 |\n| 3 | 76 | [最小覆蓋子串](https://leetcode.cn/problems/minimum-window-substring/) | sliding_window → 越長越合法/求最短 | – | 5 | 5 | 4 | 29 | 帶計數表的視窗收縮，大廠經典 hard |\n| 4 | 713 | [乘積小於 K 的子陣列](https://leetcode.cn/problems/subarray-product-less-than-k/) | sliding_window → 求子陣列個數>越短越合法 | – | 4 | 4 | 5 | 25 | 計數型視窗的入門：每右端點貢獻 `r-l+1` |\n| 5 | 3090 | [每個字元最多出現兩次的最長子字串](https://leetcode.cn/problems/maximum-length-substring-with-two-occurrences/) | sliding_window → 越短越合法/求最長 | 1329 | 4 | 4 | 3 | 23 | 小型但很新的頻率視窗題，練習「超過上限就收縮」 |\n| 6 | 2958 | [最多 K 個重複元素的最長子陣列](https://leetcode.cn/problems/length-of-longest-subarray-with-at-most-k-frequency/) | sliding_window → 越短越合法/求最長 | 1535 | 4 | 4 | 4 | 24 | 近年「至多 K 次頻率」視窗代表題，練習計數表收縮條件 |\n| 7 | 1004 | [最大連續 1 的個數 III](https://leetcode.cn/problems/max-consecutive-ones-iii/) | sliding_window → 越短越合法/求最長 | 1656 | 5 | 4 | 4 | 27 | 「至多 K 次操作」型視窗，變形極多 |\n| 8 | 2962 | [統計最大元素出現至少 K 次的子陣列](https://leetcode.cn/problems/count-subarrays-where-max-element-appears-at-least-k-times/) | sliding_window → 求子陣列個數>越長越合法 | 1701 | 4 | 4 | 4 | 24 | 固定右端點計數的近年題，補足「至少 K 次」方向 |\n| 9 | 3208 | [交替組 II](https://leetcode.cn/problems/alternating-groups-ii/) | sliding_window → 固定長度/環形視窗 | 1722 | 4 | 4 | 4 | 24 | 環形陣列上的固定長度視窗，補足取模與延展陣列技巧 |\n| 10 | 2831 | [找出最長等值子陣列](https://leetcode.cn/problems/find-the-longest-equal-subarray/) | sliding_window → 至多刪除 K 個/求最長 | 1976 | 4 | 3 | 5 | 23 | 把同值位置抽出後做視窗，練習模型轉換與刪除成本 |\n| 11 | 992 | [K 個不同整數的子陣列](https://leetcode.cn/problems/subarrays-with-k-different-integers/) | sliding_window → 恰好型滑動視窗 | 2210 | 4 | 3 | 5 | 23 | 恰好 K ＝ 至多 K − 至多 K-1，一招解一族 |",
        },
        {
          id: 32,
          title: "2.2 二分搜尋（11 題）",
          description:
            "建立邊界二分與答案二分的統一心智模型；每題都要能說清 predicate、單調性與搜尋區間。",
          summary:
            "本節將二分搜尋統一成「在單調 predicate 上找真假分界」。一條主線處理旋轉陣列與峰值等邊界判斷；另一條主線把最佳化問題改寫成 `check(x)`，再搜尋最小可行或最大可行答案。\n\n完成本節後，應能在寫程式前先口述搜尋區間、predicate 的定義、單調方向，以及迴圈結束時答案落在哪個邊界。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 33 | [搜尋旋轉排序陣列](https://leetcode.cn/problems/search-in-rotated-sorted-array/) | binary_search → 其他 | – | 5 | 5 | 4 | 29 | 旋轉陣列判「哪半邊有序」，screen 常青題 |\n| 2 | 153 | [尋找旋轉排序陣列中的最小值](https://leetcode.cn/problems/find-minimum-in-rotated-sorted-array/) | binary_search → 其他 | – | 5 | 4 | 4 | 27 | 33 的前置：先會找最小值再做搜尋 |\n| 3 | 410 | [分割陣列的最大值](https://leetcode.cn/problems/split-array-largest-sum/) | binary_search → 最小化最大值 | – | 4 | 4 | 5 | 25 | 最小化最大值代表題，亦可對照劃分型 DP 解法 |\n| 4 | 162 | [尋找峰值](https://leetcode.cn/problems/find-peak-element/) | binary_search → 其他 | – | 4 | 4 | 4 | 24 | 在「無序但有梯度」陣列上二分，考觀念非模板 |\n| 5 | 2300 | [咒語和藥水的成功對數](https://leetcode.cn/problems/successful-pairs-of-spells-and-potions/) | binary_search → 排序後查邊界 | 1477 | 4 | 4 | 4 | 24 | 排序後對每個查詢二分第一個成功位置，常見批量查詢模板 |\n| 6 | 2187 | [完成旅途的最少時間](https://leetcode.cn/problems/minimum-time-to-complete-trips/) | binary_search → 求最小 | 1641 | 4 | 4 | 4 | 24 | 旅途時間單調可行，延續 875/1011 的答案二分模板 |\n| 7 | 2226 | [每個小孩最多能分到多少糖果](https://leetcode.cn/problems/maximum-candies-allocated-to-k-children/) | binary_search → 求最大 | 1646 | 4 | 4 | 4 | 24 | 最大化可分配數量，練習搜尋最大可行值與除法 check |\n| 8 | 1011 | [在 D 天內送達包裹的能力](https://leetcode.cn/problems/capacity-to-ship-packages-within-d-days/) | binary_search → 求最小 | 1725 | 5 | 5 | 4 | 29 | 容量二分，與 875 同型但 check 寫法不同 |\n| 9 | 875 | [愛吃香蕉的珂珂](https://leetcode.cn/problems/koko-eating-bananas/) | binary_search → 求最小 | 1766 | 5 | 5 | 5 | 30 | 答案二分的標準模板：速率單調可行 |\n| 10 | 2594 | [修車的最少時間](https://leetcode.cn/problems/minimum-time-to-repair-cars/) | binary_search → 求最小 | 1915 | 4 | 4 | 4 | 24 | 時間上界二分，check 需處理平方根與大數溢位 |\n| 11 | 2517 | [禮盒的最大甜蜜度](https://leetcode.cn/problems/maximum-tastiness-of-candy-basket/) | binary_search → 最大化最小值 | 2021 | 4 | 3 | 5 | 23 | 最大化間距的答案二分，check 用貪心放置證明可行性 |",
        },
        {
          id: 33,
          title: "2.3 單調堆疊與單調佇列（10 題）",
          description:
            "用單調結構維護尚未結算的候選；掌握 next greater、貢獻邊界與滑動視窗最值三種高頻用法。",
          summary:
            "單調堆疊與單調佇列用來維護一批仍可能成為答案的候選，讓每個元素只進出結構常數次。核心能力包括：找下一個更大或更小元素、計算每個元素作為極值的貢獻區間，以及維護滑動視窗最值。\n\n完成本節後，應能解釋結構中的索引代表什麼、何時淘汰候選，以及相等元素在左右邊界上如何避免重複計數。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 739 | [每日溫度](https://leetcode.cn/problems/daily-temperatures/) | monotonic_stack → 基礎 | – | 5 | 5 | 5 | 30 | next-greater 第一模板，所有單調堆疊題的根 |\n| 2 | 239 | [滑動視窗最大值](https://leetcode.cn/problems/sliding-window-maximum/) | data_structure → 佇列>單調佇列 | – | 5 | 5 | 5 | 30 | 單調佇列唯一必會題：deque 隊首過期、隊尾彈劣 |\n| 3 | 84 | [柱狀圖中最大的矩形](https://leetcode.cn/problems/largest-rectangle-in-histogram/) | monotonic_stack → 矩形 | – | 5 | 4 | 5 | 28 | 左右第一個更小元素夾出矩形，85 題直接複用 |\n| 4 | 42 | [接雨水](https://leetcode.cn/problems/trapping-rain-water/) | monotonic_stack → 矩形 | – | 5 | 5 | 3 | 28 | 出場率極高；同時掌握雙指標與堆疊兩種解法 |\n| 5 | 2104 | [子陣列範圍和](https://leetcode.cn/problems/sum-of-subarray-ranges/) | monotonic_stack → 貢獻法 | 1504 | 4 | 4 | 4 | 24 | 同時算子陣列最大值與最小值貢獻，是 907 的自然延伸 |\n| 6 | 2398 | [預算內的最多機器人數目](https://leetcode.cn/problems/maximum-number-of-robots-within-budget/) | data_structure → 佇列>單調佇列 | 1917 | 4 | 3 | 5 | 23 | 單調佇列結合滑動視窗成本式，考驗候選淘汰與預算收縮 |\n| 7 | 2762 | [不間斷子陣列](https://leetcode.cn/problems/continuous-subarrays/) | data_structure → 佇列>單調佇列 | 1940 | 4 | 4 | 4 | 24 | 同時維護視窗最大最小值，單調雙端佇列實戰感強 |\n| 8 | 907 | [子陣列的最小值之和](https://leetcode.cn/problems/sum-of-subarray-minimums/) | monotonic_stack → 貢獻法 | 1976 | 4 | 3 | 5 | 23 | 貢獻法模板：算每個元素管轄的子陣列數 |\n| 9 | 2866 | [美麗塔 II](https://leetcode.cn/problems/beautiful-towers-ii/) | monotonic_stack → 貢獻/左右延展 | 2072 | 4 | 3 | 5 | 23 | 用單調堆疊算每個峰值向左右延展的總和，是貢獻法進階 |\n| 10 | 2444 | [統計定界子陣列的數目](https://leetcode.cn/problems/count-subarrays-with-fixed-bounds/) | sliding_window → 定界子陣列/單調邊界 | 2093 | 4 | 3 | 5 | 23 | 固定 min/max 邊界的計數題，訓練最後非法位置與貢獻計算 |",
        },
        {
          id: 34,
          title: "2.4 資料結構（14 題）",
          description:
            "練習依操作需求選擇雜湊表、堆疊、堆、並查集或 Trie，並能說明狀態、不變式與複雜度。",
          summary:
            "資料結構題考的是能否把操作需求翻成合適的狀態與容器，而不是記住容器名稱。本節覆蓋字首和＋雜湊表、堆疊消除、堆、並查集、Trie，以及資料流中位數等高頻設計情境。\n\n完成本節後，應能先列出需要支援的更新與查詢，再選擇資料結構並說明其不變式、操作複雜度與失效邊界。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 560 | [和為 K 的子陣列](https://leetcode.cn/problems/subarray-sum-equals-k/) | data_structure → 字首和>字首和與雜湊表 | – | 5 | 5 | 5 | 30 | 字首和＋雜湊計數的根模板，衍生題極多 |\n| 2 | 23 | [合併 K 個升序連結串列](https://leetcode.cn/problems/merge-k-sorted-lists/) | data_structure → 堆>進階 | – | 5 | 5 | 4 | 29 | K 路歸併＝堆的招牌用法，也練連結串列操作 |\n| 3 | 253 | [會議室 II](https://leetcode.cn/problems/meeting-rooms-ii/) | data_structure → 堆>基礎 | – | 5 | 5 | 4 | 29 | 排序＋最小堆追蹤最早結束，screen 高頻 |\n| 4 | 155 | [最小堆疊](https://leetcode.cn/problems/min-stack/) | data_structure → 堆疊>進階 | – | 5 | 4 | 3 | 26 | 「設計一個類」題型入門，輔助堆疊思想 |\n| 5 | 721 | [賬戶合併](https://leetcode.cn/problems/accounts-merge/) | data_structure → 並查集>基礎 | – | 4 | 4 | 5 | 25 | DSU 模板＋實務感很強的建模，一題打通並查集 |\n| 6 | 295 | [資料流的中位數](https://leetcode.cn/problems/find-median-from-data-stream/) | data_structure → 堆>對頂堆 | – | 4 | 4 | 4 | 24 | 對頂堆設計題，資料流題型代表 |\n| 7 | 735 | [小行星碰撞](https://leetcode.cn/problems/asteroid-collision/) | data_structure → 堆疊>鄰項消除 | – | 4 | 4 | 4 | 24 | 堆疊模擬消除，面試愛考的「會碰撞的模擬」 |\n| 8 | 208 | [實現 Trie（字首樹）](https://leetcode.cn/problems/implement-trie-prefix-tree/) | data_structure → 字典樹>基礎 | – | 4 | 3 | 4 | 22 | 唯一保留的 Trie 題：會手寫節點結構即可 |\n| 9 | 2336 | [無限集中的最小數字](https://leetcode.cn/problems/smallest-number-in-infinite-set/) | data_structure → 設計>堆/有序集合 | 1375 | 4 | 3 | 4 | 22 | 小而新的設計題，考懶新增與最小可用值維護 |\n| 10 | 2349 | [設計數字容器系統](https://leetcode.cn/problems/design-a-number-container-system/) | data_structure → 設計>有序集合/堆 | 1540 | 4 | 4 | 4 | 24 | 近年設計題，要求雜湊表與可取最小索引的容器協作 |\n| 11 | 974 | [和可被 K 整除的子陣列](https://leetcode.cn/problems/subarray-sums-divisible-by-k/) | data_structure → 字首和>字首和與雜湊表 | 1676 | 4 | 4 | 4 | 24 | 560 的同餘變形，注意 C++ 負數取模 |\n| 12 | 2353 | [設計食物評分系統](https://leetcode.cn/problems/design-a-food-rating-system/) | data_structure → 設計>有序集合/堆 | 1782 | 4 | 3 | 5 | 23 | 多鍵排序設計題，練評分更新、字典序 tie-break 與懶刪除 |\n| 13 | 2034 | [股票價格波動](https://leetcode.cn/problems/stock-price-fluctuation/) | data_structure → 設計>資料流/有序集合 | 1832 | 4 | 3 | 5 | 23 | 股票資料流設計題，練雜湊修正與有序結構取 min/max |\n| 14 | 2402 | [會議室 III](https://leetcode.cn/problems/meeting-rooms-iii/) | data_structure → 堆>區間並發 | 2093 | 4 | 3 | 5 | 23 | 會議室 II 的近年升級版，補上雙堆與延後會議模擬 |",
        },
        {
          id: 35,
          title: "2.5 網格圖（11 題）",
          description:
            "從 flood fill 進階到多源、帶狀態與 0-1 BFS；重點是正確定義狀態、visited 維度與邊權。",
          summary:
            "網格題本質上是隱式圖搜尋。本節從 flood fill 與等權最短路開始，逐步加入多源起點、額外資源狀態與 0/1 邊權，練習何時使用 DFS、普通 BFS 或 0-1 BFS。\n\n完成本節後，應能先定義完整狀態與轉移，再決定 `visited` 或 `dist` 的維度；同一座標若剩餘資源不同，必須能判斷是否應視為不同狀態。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 200 | [島嶼數量](https://leetcode.cn/problems/number-of-islands/) | grid → 網格圖 DFS | – | 5 | 5 | 5 | 30 | flood fill 根模板，幾乎是 screen 必備 |\n| 2 | 417 | [太平洋大西洋水流問題](https://leetcode.cn/problems/pacific-atlantic-water-flow/) | grid → 網格圖 DFS | – | 5 | 4 | 4 | 27 | 反向思維：從邊界倒灌兩次 DFS 取交集 |\n| 3 | 994 | [腐爛的橘子](https://leetcode.cn/problems/rotting-oranges/) | grid → 網格圖 BFS | 1433 | 5 | 5 | 5 | 30 | 多源 BFS 模板：所有源點先入隊、逐層擴散 |\n| 4 | 2658 | [網格圖中魚的最大數目](https://leetcode.cn/problems/maximum-number-of-fish-in-a-grid/) | grid → 網格圖 DFS/BFS | 1490 | 4 | 4 | 4 | 24 | 近年 flood fill 變形，適合檢查連通塊加總模板是否穩 |\n| 5 | 1926 | [迷宮中離入口最近的出口](https://leetcode.cn/problems/nearest-exit-from-entrance-in-maze/) | grid → 網格圖 BFS | 1638 | 4 | 4 | 4 | 24 | 標準迷宮最短路，練習邊界出口與起點不算出口的細節 |\n| 6 | 1091 | [二進位制矩陣中的最短路徑](https://leetcode.cn/problems/shortest-path-in-binary-matrix/) | grid → 網格圖 BFS | 1658 | 5 | 4 | 4 | 27 | 八方向最短路 BFS，邊權為 1 的標準形 |\n| 7 | 2146 | [價格範圍內最高排名的 K 樣物品](https://leetcode.cn/problems/k-highest-ranked-items-within-a-price-range/) | grid → 網格圖 BFS | 1837 | 4 | 3 | 4 | 22 | BFS 距離加排名排序，練搜尋結果的多鍵排序輸出 |\n| 8 | 1293 | [網格中的最短路徑](https://leetcode.cn/problems/shortest-path-in-a-grid-with-obstacles-elimination/) | grid → 網格圖 BFS | 1967 | 4 | 3 | 5 | 23 | visited 升維（座標＋剩餘消除數），帶狀態 BFS 代表 |\n| 9 | 1368 | [使網格圖至少有一條有效路徑的最小代價](https://leetcode.cn/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/) | grid → 0-1 BFS | 2069 | 4 | 3 | 5 | 23 | 0-1 BFS 模板：0 邊 push_front、1 邊 push_back |\n| 10 | 2290 | [到達角落需要移除障礙物的最小數目](https://leetcode.cn/problems/minimum-obstacle-removal-to-reach-corner/) | grid → 0-1 BFS | 2138 | 4 | 3 | 5 | 23 | 0-1 BFS 的近年代表，與 1368 一起鞏固 deque 最短路 |\n| 11 | 2812 | [找出最安全路徑](https://leetcode.cn/problems/find-the-safest-path-in-a-grid/) | grid → 多源 BFS + 二分/DSU | 2154 | 4 | 3 | 5 | 23 | 先多源 BFS 算安全距離，再用二分或並查集找最大瓶頸路徑 |",
        },
        {
          id: 36,
          title: "2.6 圖論演算法（12 題）",
          description:
            "聚焦依賴關係、連通分量、隱式狀態圖與最短路；目標是先完成建模，再選擇合適的圖演算法。",
          summary:
            "圖論題的第一步是建模：先說清楚節點、邊、方向與邊權，再選擇搜尋或最短路演算法。本節聚焦 coding phone screen 最常見的依賴關係、連通分量、隱式狀態圖與單源最短路。\n\n完成本節後，應能根據「是否有方向、是否要檢查環、邊權是否相等、狀態是否含額外限制」選擇 DFS、BFS、拓撲排序或 Dijkstra。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 207 | [課程表](https://leetcode.cn/problems/course-schedule/) | graph → 拓撲排序 | – | 5 | 5 | 5 | 30 | 拓撲＋環檢測模板，依賴關係題的根 |\n| 2 | 210 | [課程表 II](https://leetcode.cn/problems/course-schedule-ii/) | graph → 拓撲排序 | – | 5 | 5 | 4 | 29 | 207 的輸出方案版，兩題一起 30 分鐘內完成 |\n| 3 | 743 | [網路延遲時間](https://leetcode.cn/problems/network-delay-time/) | graph → 單源最短路：Dijkstra | – | 5 | 4 | 5 | 28 | 堆版 Dijkstra 標準模板，背到能盲寫 |\n| 4 | 547 | [省份數量](https://leetcode.cn/problems/number-of-provinces/) | graph → 深度優先搜尋（DFS） | – | 5 | 4 | 4 | 27 | 鄰接矩陣連通分量，DFS/DSU 雙解都要會 |\n| 5 | 127 | [單詞接龍](https://leetcode.cn/problems/word-ladder/) | graph → 圖論建模 + BFS 最短路 | – | 4 | 4 | 4 | 24 | 把字串當節點的隱式圖建模，screen 經典 |\n| 6 | 752 | [開啟轉盤鎖](https://leetcode.cn/problems/open-the-lock/) | graph → 圖論建模 + BFS 最短路 | – | 4 | 4 | 4 | 24 | 狀態空間 BFS＋死鎖剪枝，與 127 同型互補 |\n| 7 | 787 | [K 站中轉內最便宜的航班](https://leetcode.cn/problems/cheapest-flights-within-k-stops/) | graph → 單源最短路：Dijkstra | – | 4 | 3 | 4 | 22 | 帶步數限制的最短路：練「狀態＝節點×步數」 |\n| 8 | 2115 | [從給定原材料中找到所有可以做出的菜](https://leetcode.cn/problems/find-all-possible-recipes-from-given-supplies/) | graph → 拓撲排序 | 1679 | 4 | 4 | 4 | 24 | 把食譜依賴建成 DAG，貼近實務依賴解析問題 |\n| 9 | 2492 | [兩個城市間路徑的最小分數](https://leetcode.cn/problems/minimum-score-of-a-path-between-two-cities/) | graph → 連通分量/DSU | 1680 | 4 | 4 | 4 | 24 | 連通分量上的路徑最小邊，DFS/DSU 都能說清楚 |\n| 10 | 2359 | [找到離給定兩個節點最近的節點](https://leetcode.cn/problems/find-closest-node-to-given-two-nodes/) | graph → 有向圖 DFS | 1715 | 4 | 3 | 4 | 22 | 每點出度至多一的近年圖題，練距離標記與雙源比較 |\n| 11 | 2192 | [有向無環圖中一個節點的所有祖先](https://leetcode.cn/problems/all-ancestors-of-a-node-in-a-directed-acyclic-graph/) | graph → 拓撲排序 | 1788 | 4 | 3 | 5 | 23 | DAG 祖先集合傳遞，補強拓撲序上的狀態合併 |\n| 12 | 2608 | [圖中的最短環](https://leetcode.cn/problems/shortest-cycle-in-a-graph/) | graph → BFS 最短環 | 1904 | 4 | 3 | 5 | 23 | 無向圖最短環模板，練從每個起點 BFS 與父節點排除 |",
        },
        {
          id: 37,
          title: "2.7 動態規劃（15 題）",
          description:
            "用最後一步與狀態機思考建立 DP；涵蓋線性、背包、雙序列、劃分、網格與帶權區間排程。",
          summary:
            "動態規劃是本計畫題數最多的主題，但練習範圍刻意集中在面試中最常見的狀態設計：線性、背包、雙序列、劃分型、網格、狀態機與帶權區間排程。\n\n完成本節後，應能從暴力遞迴或「最後一步」定義狀態，寫出轉移、初始化與計算順序，並判斷何時能做空間壓縮或改用其他演算法。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 198 | [打家劫舍](https://leetcode.cn/problems/house-robber/) | dynamic_programming → 入門 DP>打家劫舍 | – | 5 | 5 | 5 | 30 | 「選或不選」狀態定義的根，先把遞迴→遞推走一遍 |\n| 2 | 322 | [零錢兌換](https://leetcode.cn/problems/coin-change/) | dynamic_programming → 背包>完全背包 | – | 5 | 5 | 5 | 30 | 完全背包模板，screen DP 出題熱區 |\n| 3 | 300 | [最長遞增子序列](https://leetcode.cn/problems/longest-increasing-subsequence/) | dynamic_programming → 經典線性 DP>LIS 基礎 | – | 5 | 5 | 5 | 30 | O(n²) DP 與 O(n log n) 貪心+二分都要會講 |\n| 4 | 139 | [單詞拆分](https://leetcode.cn/problems/word-break/) | dynamic_programming → 劃分型 DP>判定能否劃分 | – | 5 | 5 | 4 | 29 | 劃分型 DP 入門：「最後一段從哪切」思考法 |\n| 5 | 1143 | [最長公共子序列](https://leetcode.cn/problems/longest-common-subsequence/) | dynamic_programming → 經典線性 DP>LCS 基礎 | – | 5 | 4 | 5 | 28 | 雙序列 DP 的根模板 |\n| 6 | 416 | [分割等和子集](https://leetcode.cn/problems/partition-equal-subset-sum/) | dynamic_programming → 背包>0-1 背包 | – | 5 | 4 | 5 | 28 | 0-1 背包＋bool 可行性，倒序枚舉容量是考點 |\n| 7 | 64 | [最小路徑和](https://leetcode.cn/problems/minimum-path-sum/) | dynamic_programming → 網格圖 DP>基礎 | – | 5 | 4 | 4 | 27 | 網格 DP 標準形，與網格 BFS 區分使用時機 |\n| 8 | 72 | [編輯距離](https://leetcode.cn/problems/edit-distance/) | dynamic_programming → 經典線性 DP>LCS 基礎 | – | 5 | 4 | 4 | 27 | LCS 框架上的三操作轉移，大廠經典 |\n| 9 | 309 | [買賣股票的最佳時機含冷凍期](https://leetcode.cn/problems/best-time-to-buy-and-sell-stock-with-cooldown/) | dynamic_programming → 狀態機 DP>買賣股票 | – | 4 | 4 | 5 | 25 | 狀態機 DP 代表：畫出持有/冷凍/空倉三態轉移圖 |\n| 10 | 2466 | [統計構造好字串的方案數](https://leetcode.cn/problems/count-ways-to-build-good-strings/) | dynamic_programming → 線性 DP>計數 | 1694 | 4 | 4 | 4 | 24 | 一維計數 DP，練狀態累加與模數處理 |\n| 11 | 2140 | [解決智力問題](https://leetcode.cn/problems/solving-questions-with-brainpower/) | dynamic_programming → 入門 DP>倒序線性 DP | 1709 | 4 | 4 | 4 | 24 | 近年線性 DP 常考題，練習「做/不做」與跳轉下標 |\n| 12 | 2786 | [訪問陣列中的位置使分數最大](https://leetcode.cn/problems/visit-array-positions-to-maximize-score/) | dynamic_programming → 狀態機 DP>奇偶狀態 | 1733 | 4 | 3 | 5 | 23 | 兩狀態最大分數 DP，補強狀態機在陣列選擇上的應用 |\n| 13 | 2707 | [字串中的額外字元](https://leetcode.cn/problems/extra-characters-in-a-string/) | dynamic_programming → 劃分型 DP>字典匹配 | 1736 | 4 | 4 | 4 | 24 | 字串劃分 DP，與 139 同型但目標改為最小剩餘字元 |\n| 14 | 2369 | [檢查陣列是否存在有效劃分](https://leetcode.cn/problems/check-if-there-is-a-valid-partition-for-the-array/) | dynamic_programming → 劃分型 DP>判定能否劃分 | 1780 | 4 | 3 | 5 | 23 | 小段合法性劃分，延續 139 的最後一段思考法 |\n| 15 | 1235 | [規劃兼職工作](https://leetcode.cn/problems/maximum-profit-in-job-scheduling/) | technical_interview → 排程決策與動態規劃 | 2023 | 4 | 4 | 5 | 25 | 帶權區間排程：排序＋二分前驅，工程感最強的 DP |",
        },
        {
          id: 38,
          title: "2.8 樹和二元樹（11 題）",
          description:
            "練習設計遞迴函式的回傳值與全域答案；掌握 LCA、直徑與路徑和、BST，以及層序遍歷。",
          summary:
            "樹題的核心是定義每個遞迴呼叫要向父節點回傳什麼，以及答案是在回傳值中形成，還是在遍歷過程中另外更新。本節涵蓋 LCA、直徑與路徑和、BST 性質，以及層序與深度優先遍歷。\n\n完成本節後，應能在寫 DFS 前先說清楚 base case、回傳值語意、左右子樹如何合併，以及最壞遞迴深度。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 236 | [二叉樹的最近公共祖先](https://leetcode.cn/problems/lowest-common-ancestor-of-a-binary-tree/) | trees → 二叉樹>最近公共祖先 | – | 5 | 5 | 5 | 30 | LCA 遞迴模板，screen 樹題第一熱門 |\n| 2 | 543 | [二叉樹的直徑](https://leetcode.cn/problems/diameter-of-binary-tree/) | trees → 二叉樹>二叉樹的直徑 | – | 5 | 5 | 5 | 30 | 「回傳鏈長、過程中更新答案」的根模板 |\n| 3 | 124 | [二叉樹中的最大路徑和](https://leetcode.cn/problems/binary-tree-maximum-path-sum/) | trees → 二叉樹>二叉樹的直徑 | – | 5 | 4 | 5 | 28 | 543 的帶權版＋負數剪枝，hard 樹題代表 |\n| 4 | 98 | [驗證二叉搜索樹](https://leetcode.cn/problems/validate-binary-search-tree/) | trees → 二叉樹>二叉搜索樹 | – | 5 | 4 | 4 | 27 | 上下界傳遞或中序遞增，兩種寫法都要會 |\n| 5 | 199 | [二叉樹的右檢視](https://leetcode.cn/problems/binary-tree-right-side-view/) | trees → 二叉樹>自頂向下 DFS | – | 4 | 4 | 4 | 24 | 層序 BFS 與「深度優先先右後左」雙解 |\n| 6 | 230 | [二叉搜索樹中第 K 小的元素](https://leetcode.cn/problems/kth-smallest-element-in-a-bst/) | trees → 二叉樹>二叉搜索樹 | – | 4 | 4 | 4 | 24 | 中序遍歷提前終止，BST 性質的標準應用 |\n| 7 | 2583 | [二叉樹中的第 K 大層和](https://leetcode.cn/problems/kth-largest-sum-in-a-binary-tree/) | trees → 二叉樹>層序遍歷 | 1374 | 4 | 4 | 3 | 23 | 層序聚合題，練 BFS 分層與取第 K 大 |\n| 8 | 2471 | [逐層排序二叉樹所需的最少運算元目](https://leetcode.cn/problems/minimum-number-of-operations-to-sort-a-binary-tree-by-level/) | trees → 二叉樹>層序遍歷 | 1635 | 4 | 3 | 4 | 22 | 逐層排序與最少交換次數，結合 BFS 與置換環 |\n| 9 | 2641 | [二叉樹的堂兄弟節點 II](https://leetcode.cn/problems/cousins-in-binary-tree-ii/) | trees → 二叉樹>層序遍歷 | 1677 | 4 | 3 | 4 | 22 | 近年層序更新題，考同層總和與原值暫存順序 |\n| 10 | 2385 | [感染二叉樹需要的總時間](https://leetcode.cn/problems/amount-of-time-for-binary-tree-to-be-infected/) | trees → 二叉樹>圖化 BFS | 1711 | 4 | 4 | 4 | 24 | 將二叉樹轉成無向圖做層序擴散，補足父指標建模 |\n| 11 | 2477 | [到達首都的最少油耗](https://leetcode.cn/problems/minimum-fuel-cost-to-report-to-the-capital/) | trees → 樹形 DFS>子樹聚合 | 2012 | 4 | 4 | 4 | 24 | 樹上自底向上統計人數與油耗，工程敘事很接近實務建模 |",
        },
        {
          id: 39,
          title: "2.9 貪心與區間（10 題）",
          description:
            "聚焦可證明且可模板化的貪心：排序掃描、區間選擇與最遠可達；每題都要能解釋局部選擇為何安全。",
          summary:
            "本節只保留能在面試中清楚論證、也能快速實作的貪心模型：排序後掃描區間、按右端點選擇，以及維護最遠可達範圍。重點不是看到最佳化就猜貪心，而是說明局部選擇為何不會排除全域最佳解。\n\n完成本節後，應能辨認排序鍵、維護的摘要狀態與交換論證或覆蓋論證，並主動檢查相等端點與空集合等邊界。\n\n| # | LC ID | Title | Sub-section in lecture | Rating | I | F | L | Score | Why it matters |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 1 | 56 | [合併區間](https://leetcode.cn/problems/merge-intervals/) | greedy → 合併區間 | – | 5 | 5 | 5 | 30 | 排序後一次掃描，區間題第一模板 |\n| 2 | 55 | [跳躍遊戲](https://leetcode.cn/problems/jump-game/) | greedy → 合併區間 | – | 5 | 5 | 4 | 29 | 「最遠可達」貪心，與 45 成對 |\n| 3 | 435 | [無重疊區間](https://leetcode.cn/problems/non-overlapping-intervals/) | greedy → 不相交區間 | – | 5 | 4 | 5 | 28 | 按右端點排序選最多不相交區間的經典證明 |\n| 4 | 763 | [劃分字母區間](https://leetcode.cn/problems/partition-labels/) | greedy → 合併區間 | – | 4 | 4 | 4 | 24 | 記每個字元最遠位置再掃描，合併區間的變形 |\n| 5 | 45 | [跳躍遊戲 II](https://leetcode.cn/problems/jump-game-ii/) | greedy → 區間覆蓋 | – | 4 | 4 | 4 | 24 | 區間覆蓋式分層貪心，55 的求步數版 |\n| 6 | 2279 | [裝滿石頭的揹包的最大數量](https://leetcode.cn/problems/maximum-bags-with-full-capacity-of-rocks/) | greedy → 排序填充 | 1249 | 4 | 4 | 3 | 23 | 排序後優先補最小缺口，簡潔但能練交換論證 |\n| 7 | 2410 | [運動員和訓練師的最大匹配數](https://leetcode.cn/problems/maximum-matching-of-players-with-trainers/) | greedy → 排序雙指標 | 1381 | 4 | 4 | 3 | 23 | 雙指標匹配模板，與區間選擇同樣依賴排序後局部最優 |\n| 8 | 2406 | [將區間分為最少組數](https://leetcode.cn/problems/divide-intervals-into-minimum-number-of-groups/) | greedy → 區間分組 | 1713 | 4 | 4 | 4 | 24 | 區間並發最少組數，能用堆或差分說清楚貪心含義 |\n| 9 | 2439 | [最小化陣列中的最大值](https://leetcode.cn/problems/minimize-maximum-of-array/) | greedy → 前綴最大值 | 1965 | 4 | 3 | 5 | 23 | 用前綴平均值下界推答案，訓練可證明的全域貪心 |\n| 10 | 2366 | [將陣列排序的最少替換次數](https://leetcode.cn/problems/minimum-replacements-to-sort-the-array/) | greedy → 逆序掃描 | 2060 | 4 | 3 | 5 | 23 | 從右往左維持上界的近年貪心題，重點是拆分次數推導 |",
        },
      ],
    },
    {
      id: 9,
      title: "3. 已捨棄的章節",
      description:
        "說明衝刺期刻意不練的低頻或高成本主題，幫助你守住時間預算，避免被完整度焦慮拖慢。",
      summary:
        "衝刺計畫的價值來自取捨。以下章節在 18 天 × 60 題的時間預算下暫不安排，不代表它們不重要，而是其出題頻率、學習成本或可遷移性低於本計畫保留的主題。若目標改為競賽、onsite 或更長期準備，再依需要補回。\n\n- **rating_2100（整章）**：四個 Phase 與各主題章節大量重複，衝刺期直接做主題章節效率更高。\n- **string → KMP/Z 函式/Manacher/AC 自動機/後綴陣列與自動機**：字串自動機族在 phone screen 出現率趨近於零。\n- **math（整章：數論/組合/博弈 SG/幾何/多項式/FWT）**：contest 專屬知識，45 分鐘 screen 不考。\n- **bitwise_operations → 線性基/試填法/LogTrick/恆等式**：純競賽位元技巧，學習槓桿低。\n- **data_structure → 樹狀陣列/線段樹/莫隊/根號分解/可持久化/Splay/離線演算法**：實作成本遠超 45 分鐘上限，性價比最差的一塊。\n- **dynamic_programming → 數位 DP/狀壓 DP/輪廓線/SOS/斜率優化/WQS 二分/矩陣快速冪**：高成本低頻率，1800+ 補洞應優先補狀態機與劃分型。\n- **graph → 網路流/尤拉路徑/強連通分量/二分圖染色/基環樹/差分約束**：超出 screen 範圍，留到 onsite 前再說。\n- **trees → 倍增 LCA/虛樹/點分治/樹上啟發式合併/DFS 時間戳**：樹分解進階主題，模板長且出題率低。\n- **greedy → 交換論證/構造題/互動題/腦筋急轉彎/數學貪心**：不可模板化、訊號低；只保留區間貪心族。\n- **sorting（整章：計數/基數/桶排序）**：幾乎不單獨出題，知道概念即可。\n- **sliding_window → 分組迴圈/三指標/原地修改/背向雙指標等雜項**：雜項小節以主模板帶過即可。\n- **technical_interview → 距離向量與幾何/掃描線/狀態空間壓縮 BFS/高階 DP 小節**：已抽出 875、1011、1235、1293 等代表題進入題單，其餘屬 2200+ 難度區，超出目標。",
    },
  ],
} as TutorialData.Root;
