import type { TutorialData } from "@/types";
import technicalInterviewPractice from "@/public/studyplan/technical_interview.json";

const problemTableHeader =
  "| ID | Problem | Rating | Labels |\n| --- | --- | --- | --- |";

type PracticeProblem = {
  id: string | number;
  title: string;
  slug: string;
  src?: string;
  score?: number | null;
  subsection?: string | null;
};

type PracticeSection = {
  id: number;
  problems?: PracticeProblem[];
};

const practiceSections =
  technicalInterviewPractice.children as PracticeSection[];

function problemToTableRow(problem: PracticeProblem) {
  const href = problem.src ?? `https://leetcode.cn/problems/${problem.slug}/`;
  const rating =
    typeof problem.score === "number"
      ? Math.round(problem.score).toString()
      : "";
  return `| ${problem.id} | [${problem.title}](${href}) | ${rating} | ${problem.subsection ?? ""} |`;
}

function practiceRowsForSection(sectionId: number) {
  return (
    practiceSections
      .find((section) => section.id === sectionId)
      ?.problems?.map(problemToTableRow) ?? []
  );
}

/** Deduped problem rows pulled from a set of practice sections, used to build
 *  the category-organised summary tables at the end of the lecture. */
function categoryRows(sectionIds: number[]) {
  const seen = new Set<string>();
  return sectionIds
    .flatMap(
      (id) =>
        practiceSections.find((section) => section.id === id)?.problems ?? [],
    )
    .filter((problem) => {
      const key = `${problem.id}:${problem.slug}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .map(problemToTableRow);
}

function allPracticeRows() {
  const seen = new Set<string>();
  return practiceSections.flatMap((section) =>
    (section.problems ?? [])
      .filter((problem) => {
        const key = `${problem.id}:${problem.slug}`;
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
      })
      .map(problemToTableRow),
  );
}

/** Join authored lines into a markdown summary. Keeps long, code-heavy section
 *  bodies readable in source while still emitting a single markdown string. */
function md(...lines: string[]) {
  return lines.join("\n");
}

function withPractice(summary: string, rows: string[]) {
  return `${summary}\n\n**搭配練習**\n\n${problemTableHeader}\n${rows.join("\n")}`;
}

function withSectionPractice(summary: string, sectionId: number) {
  return withPractice(summary, practiceRowsForSection(sectionId));
}

export const technicalInterview = {
  id: 1,
  title: "技術面試準備",
  src: "",
  last_update: "2026-06-13T00:00:00.000Z",
  summary: md(
    "這份題單針對**高效能、即時、運算密集型 ML 系統**的高階技術面試整理背景知識：不只練演算法題型，更把每一章連回實際系統裡的效能瓶頸——資料流排程、張量／網格的記憶體佈局、執行 DAG 的關鍵路徑、量測與調校。題目本身是公司無關的 LeetCode 風格題，目的是用可量化的小題反覆訓練同一組底層直覺。",
    "",
    "**章節地圖**：前段（1–14）是核心演算法主題，每章先講「何時用、面試先問自己什麼、複雜度」，再補一段**效能工程視角**，把題型對應到真實系統的瓶頸與 C++ 實作邊界。後段（15–20）標記 `[ADVANCED / NICHE]`，涵蓋一般面試準備較少觸及、但高階效能工程常被深問的主題：記憶體階層與資料佈局、SIMD 與 branchless、多執行緒與 lock-free、硬體感知 ML（roofline／分塊／算術強度）、數值精度與量化、效能量測與 profiling 方法論。第 21 章把所有題目依類別（圖／BFS-DFS、堆積、2D／幾何、雜湊與設計、DP／組合）整理成總表。",
    "",
    "**使用方式**：先讀觀念與效能視角，限時做題，再用題型訊號反推自己的程式碼；凡標 `[ADVANCED / NICHE]` 的段落代表超出常見面試範圍的補充知識，讀者可依目標選讀。每題復盤五件事：題型訊號、關鍵不變式、時間／空間複雜度、記憶體上限、可替代解法。",
  ),
  children: [
    {
      id: 2,
      title: "1. 服務拓撲：圖搜尋與最短路",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "把服務拓撲、任務依賴或資料轉換流程建成圖，第一步不是套模板，而是決定節點、邊與成本的語意。等權邊用 BFS，0/1 權用 deque，非負權用 Dijkstra；若有可證明不高估的啟發式，才使用 A*。",
          "",
          "面試時要主動說清楚 visited 維度。同一個節點在不同剩餘資源、階段、mask 或時間下可能代表不同狀態，不能只用節點編號去重。回答時把「成本函數、狀態數、鬆弛條件、最壞複雜度」講完整。",
          "",
          "**效能工程視角**",
          "",
          "在運算密集系統裡，這個圖往往就是**運算核心（kernel）之間的資料流圖**：節點是算子，邊是張量依賴，邊權是核心耗時或記憶體搬移成本。最短路／關鍵路徑決定了端到端延遲，而「同一算子在不同放置（device/stream）下成本不同」正是上面講的 visited 多維度問題。面試官會看你能不能把抽象圖題講回延遲預算。",
          "",
          "[ADVANCED / NICHE] Dijkstra 的常數因子在大圖上很關鍵：用陣列式索引堆而非節點物件、避免 `unordered_map` 的雜湊成本、用 lazy deletion 取代 `decrease-key`，都是把 `O((V+E) log V)` 的常數壓低的實作慣例。",
          "",
          ":::example Dijkstra：lazy deletion 版（陣列鄰接表、最小堆，避免 decrease-key）",
          "把鄰接表存成扁平陣列、距離放 `vector<long long>`、堆裡放 `{dist, node}`，過期項在彈出時用 `d > dist[u]` 跳過。這版的記憶體連續、cache 友善，是工程上預設寫法。",
          "",
          "```cpp",
          "// Dijkstra：非負權單源最短路，lazy deletion 版",
          "vector<long long> dijkstra(int n, const vector<vector<pair<int,int>>>& g, int src) {",
          "  const long long INF = (1LL << 62);",
          "  vector<long long> dist(n, INF);",
          "  priority_queue<pair<long long,int>, vector<pair<long long,int>>,",
          "                 greater<>> pq;",
          "  dist[src] = 0;",
          "  pq.push({0, src});",
          "  while (!pq.empty()) {",
          "    auto [d, u] = pq.top();",
          "    pq.pop();",
          "    if (d > dist[u]) continue;  // 過期項，直接丟棄（lazy deletion）",
          "    for (auto [v, w] : g[u]) {",
          "      if (dist[u] + w < dist[v]) {",
          "        dist[v] = dist[u] + w;",
          "        pq.push({dist[v], v});",
          "      }",
          "    }",
          "  }",
          "  return dist;  // 不可達者保持 INF",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O((V+E) log V)` 時間、`O(V+E)` 空間；注意自環、重邊、`INF` 溢位（用 `long long` 並讓 `INF` 遠小於型別上限避免相加溢位）、不可達節點。",
          "",
          "**搭配練習重點**：最短路方案數、分層圖、動態邊、最大機率路徑與距離閾值查詢。",
        ),
        2,
      ),
    },
    {
      id: 3,
      title: "2. 批次矩陣與多源 BFS",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "矩陣批次處理題常問「每個位置到最近來源的距離」「哪些位置可達」「狀態是否包含方向或時間」。若來源有很多個，把所有來源同時入隊就是多源 BFS；若每一步成本不同，才升級到 0-1 BFS 或 Dijkstra。",
          "",
          "這類題的價值在於邊界與狀態控制：矩陣大小決定記憶體上限，visited 是否需要額外維度決定正確性，隊列順序決定第一次到達是否就是最短。",
          "",
          "**效能工程視角**",
          "",
          "二維批次走訪就是張量在記憶體裡的走訪：`grid[r][c]` 連續存放時，**逐列（row-major）走訪是順序存取、cache 友善**，逐行走訪則每步跨一個 row stride，容易 cache miss。面試裡能講清楚走訪順序與 stride 的關係，是效能題的基本功。",
          "",
          "[ADVANCED / NICHE] 大網格 BFS 用「扁平化 + 方向偏移」取代二維 `vector<vector<>>`：把 `(r,c)` 映成 `r*cols+c`，鄰居用 `{+1,-1,+cols,-cols}` 偏移，省去雙層 vector 的指標跳轉與配置，並讓 `visited` 變成一塊連續記憶體。",
          "",
          ":::example 多源 BFS：扁平化網格、距離場（所有來源同時入隊，距離設 0）",
          "把每個來源的距離設 0、一起入隊，第一次彈出即最短。扁平索引讓整張距離表是單一連續 buffer。",
          "",
          "```cpp",
          "// 多源 BFS：回傳每格到最近來源的距離（不可達為 -1）",
          "vector<int> multiSourceBFS(int rows, int cols,",
          "                           const vector<int>& sources) {",
          "  const int n = rows * cols;",
          "  vector<int> dist(n, -1);",
          "  queue<int> q;",
          "  for (int s : sources) {",
          "    if (dist[s] == -1) {",
          "      dist[s] = 0;",
          "      q.push(s);",
          "    }",
          "  }",
          "  const int dr[4] = {1, -1, 0, 0};",
          "  const int dc[4] = {0, 0, 1, -1};",
          "  while (!q.empty()) {",
          "    int cur = q.front();",
          "    q.pop();",
          "    int r = cur / cols, c = cur % cols;",
          "    for (int k = 0; k < 4; k++) {",
          "      int nr = r + dr[k], nc = c + dc[k];",
          "      if (nr < 0 || nr >= rows || nc < 0 || nc >= cols) continue;",
          "      int nxt = nr * cols + nc;",
          "      if (dist[nxt] != -1) continue;",
          "      dist[nxt] = dist[cur] + 1;",
          "      q.push(nxt);",
          "    }",
          "  }",
          "  return dist;",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(rows·cols)` 時間與空間；注意空來源集合、全為來源、走訪順序對 cache 的影響、邊界越界檢查。",
          "",
          "**搭配練習重點**：距離場、可達性、剩餘資源、離線矩陣查詢與時間約束搜尋。",
        ),
        3,
      ),
    },
    {
      id: 4,
      title: "3. 距離、向量與幾何判斷",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "距離、向量與幾何題訓練的是數值表示與邊界判斷。先決定資料用整數、浮點或有理數表示，再用叉積判方向、點積判投影、掃描線處理區域重疊，避免在邊界點與溢位上出錯。",
          "",
          "即使題目看起來不像系統題，面試官也會看你是否能把資料格式、精度策略與複雜度說清楚。AABB、最近距離、凸包、曼哈頓轉換都可以轉成小而穩定的原語。",
          "",
          "**效能工程視角**",
          "",
          "幾何運算（距離、點積、叉積）是規則的浮點算術，正是**向量化（SIMD）**最容易發揮的場景：N 個點的距離計算彼此獨立，可一次處理多個 lane。能用「距離平方」避免 `sqrt`、能把分支改成 `min/max`，都是讓編譯器自動向量化的前置條件。",
          "",
          "[ADVANCED / NICHE] 用「整數叉積」避免浮點誤差：判斷三點方向時 `(b-a) × (c-a)` 全程整數運算，只看正負號，不會有 epsilon 抉擇問題；但要用 `long long` 防止座標相乘溢位。",
          "",
          ":::example 叉積定向 + 距離平方（整數安全、避免 sqrt）",
          "`cross` 回傳有號面積的兩倍，正負代表逆／順時針；`dist2` 用平方比較避免開根號與精度問題。",
          "",
          "```cpp",
          "// 叉積：>0 逆時針、<0 順時針、=0 共線（座標用 long long 防溢位）",
          "long long cross(long long ax, long long ay,",
          "                long long bx, long long by,",
          "                long long cx, long long cy) {",
          "  return (bx - ax) * (cy - ay) - (by - ay) * (cx - ax);",
          "}",
          "",
          "// 距離平方：比較大小時用它取代 sqrt，避免浮點誤差",
          "long long dist2(long long ax, long long ay, long long bx, long long by) {",
          "  long long dx = ax - bx, dy = ay - by;",
          "  return dx * dx + dy * dy;",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：單次 `O(1)`；凸包／掃描線整體 `O(n log n)`。注意共線點、重合點、座標相乘溢位、`[s,e)` 與 `[s,e]` 的端點包含性。",
          "",
          "**搭配練習重點**：矩形相交、圓與矩形、凸包/可見點、最近距離與掃描線面積。",
        ),
        4,
      ),
    },
    {
      id: 5,
      title: "4. 依賴圖與執行 DAG",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "依賴圖題常來自任務階段、資料管線或服務呼叫順序。先判斷邊是有向還是無向：有向邊看拓撲排序、環檢測與 SCC；無向邊看連通塊、DSU、橋與關鍵連線。",
          "",
          "若題目問最早完成時間，在拓撲序上做 DP；若題目問逐步合併後是否連通，用 DSU；若題目問斷一條邊是否分裂，用 low-link。",
          "",
          "**效能工程視角**",
          "",
          "執行 DAG 的拓撲序就是**算子的合法執行順序**，拓撲序上的最長路徑（關鍵路徑）即無限平行下的理論最短延遲。能算關鍵路徑，就能回答「加機器還有沒有用」「哪個算子是瓶頸」這類效能問題。Kahn 演算法的 in-degree 佇列天然對應「就緒任務佇列」。",
          "",
          "[ADVANCED / NICHE] 在拓撲序上做關鍵路徑 DP：`finish[u] = cost[u] + max(finish[pred])`，整張圖一遍掃完即得端到端延遲與每個節點的 slack（可延遲而不影響總延遲的餘量）。",
          "",
          ":::example Kahn 拓撲排序 + 關鍵路徑（最早完成時間）",
          "in-degree 為 0 的節點先入佇列；每處理一個節點就鬆弛其後繼的最早完成時間，並在 in-degree 歸零時入佇列。若最終處理數 < n，代表有環。",
          "",
          "```cpp",
          "// 回傳 {是否為 DAG, 端到端最早完成時間}",
          "pair<bool,long long> criticalPath(int n,",
          "    const vector<vector<int>>& g, const vector<long long>& cost) {",
          "  vector<int> indeg(n, 0);",
          "  for (int u = 0; u < n; u++)",
          "    for (int v : g[u]) indeg[v]++;",
          "  queue<int> q;",
          "  vector<long long> finish(n, 0);",
          "  for (int u = 0; u < n; u++)",
          "    if (indeg[u] == 0) { finish[u] = cost[u]; q.push(u); }",
          "  int seen = 0;",
          "  long long makespan = 0;",
          "  while (!q.empty()) {",
          "    int u = q.front();",
          "    q.pop();",
          "    seen++;",
          "    makespan = max(makespan, finish[u]);",
          "    for (int v : g[u]) {",
          "      finish[v] = max(finish[v], finish[u] + cost[v]);",
          "      if (--indeg[v] == 0) q.push(v);",
          "    }",
          "  }",
          "  return {seen == n, makespan};  // seen != n 代表有環",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(V+E)`；注意有環（無拓撲序）、重邊、孤立節點、入度初始化。",
          "",
          "**搭配練習重點**：拓撲祖先、關鍵連線、完全連通分量、最長環與樹根計數。",
        ),
        5,
      ),
    },
    {
      id: 6,
      title: "5. 排程決策與動態規劃",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "排程與資源選擇題通常要把「目前做到哪裡」和「已用資源」寫成狀態。先寫出最後一步：最後一段從哪裡切、最後一個任務接在哪個前驅後，轉移式會自然浮現。",
          "",
          "樸素 DP 過慢時，再用排序、二分前驅、前綴最值、單調資料結構或記憶化搜尋優化。要能說清楚優化沒有改變狀態語意，只是加速找候選。",
          "",
          "**效能工程視角**",
          "",
          "排程 DP 對應的是**算子融合（fusion）與切分（partitioning）的成本模型**：把一段連續算子合併能省記憶體往返，但受片上記憶體容量限制——這正是「帶權區間排程／工作切分」的結構。會建成本模型、能解釋 DP 狀態就是工程上的「放置決策」，比硬背模板更打動面試官。",
          "",
          "[ADVANCED / NICHE] DP 的記憶體佈局也影響速度：把 `dp` 從二維壓成一維滾動陣列不只省空間，更讓熱資料留在 cache；轉移順序（i 在外、j 在內）要配合 row-major 連續存取。",
          "",
          ":::example 帶權區間排程：排序 + 二分前驅 DP",
          "按結束時間排序，`dp[i]` = 前 i 個工作的最大收益；對每個工作二分找「最後一個不衝突的前驅」，取「不選 / 選」較大者。",
          "",
          "```cpp",
          "// 帶權區間排程：每個工作 {start, end, profit}",
          "int jobScheduling(vector<array<int,3>>& jobs) {",
          "  sort(jobs.begin(), jobs.end(),",
          "       [](auto& a, auto& b) { return a[1] < b[1]; });  // 按 end 排序",
          "  int n = jobs.size();",
          "  vector<int> ends(n), dp(n + 1, 0);",
          "  for (int i = 0; i < n; i++) ends[i] = jobs[i][1];",
          "  for (int i = 0; i < n; i++) {",
          "    // 二分：最後一個 end <= 當前 start 的工作",
          "    int lo = 0, hi = i;",
          "    int s = jobs[i][0];",
          "    while (lo < hi) {",
          "      int mid = (lo + hi) / 2;",
          "      if (ends[mid] <= s) lo = mid + 1; else hi = mid;",
          "    }",
          "    dp[i + 1] = max(dp[i], dp[lo] + jobs[i][2]);  // 不選 / 選",
          "  }",
          "  return dp[n];",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(n log n)`；注意端點相接是否算衝突、收益為負、空輸入、相同結束時間的 tie-break。",
          "",
          "**搭配練習重點**：帶權區間排程、工作切分、集合選擇、狀壓 DP 與多階段最值。",
        ),
        6,
      ),
    },
    {
      id: 7,
      title: "6. 參數搜尋、貪心與滑動視窗",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "參數搜尋題的核心是單調 predicate。遇到「最小可行值」「最大可承受值」「最小最大」時，先定義 `check(x)`，再證明 `x` 變大或變小後可行性方向不會反轉。",
          "",
          "滑動視窗則要求條件能局部維護：右端加入、左端移除後，可以用計數、總和、最大值或 deque 更新合法性。貪心題要補交換論證，不能只說直覺。",
          "",
          "**效能工程視角**",
          "",
          "二分答案就是**自動調校（autotuning）**的離散版：在 batch size、tile size、執行緒數等旋鈕上找「剛好滿足延遲/記憶體約束」的設定，靠的就是單調 `check(x)`。能把調校問題講成單調 predicate 上的二分，遠比窮舉所有設定有說服力。",
          "",
          "[ADVANCED / NICHE] 二分答案的 `check(x)` 常自帶 greedy 模擬；要分析「外層 `O(log W)` × 內層 `O(n)`」的總成本，並確認值域 `W` 用 `long long` 表示時不會溢位。",
          "",
          ":::example 二分答案：最小化「最大負載」（check 用貪心切分）",
          "把陣列分成 m 段使最大段和最小：二分候選上限 `cap`，`check(cap)` 貪心地能裝就裝、裝不下就開新段，段數 <= m 即可行。",
          "",
          "```cpp",
          "// 把 nums 切成 m 段，最小化最大段和",
          "int splitArrayMinMax(const vector<int>& nums, int m) {",
          "  long long lo = 0, hi = 0;",
          "  for (int x : nums) { lo = max(lo, (long long)x); hi += x; }",
          "  auto check = [&](long long cap) {",
          "    int parts = 1;",
          "    long long cur = 0;",
          "    for (int x : nums) {",
          "      if (cur + x > cap) { parts++; cur = x; }  // 開新段",
          "      else cur += x;",
          "    }",
          "    return parts <= m;  // 段數夠少 => cap 可行",
          "  };",
          "  while (lo < hi) {",
          "    long long mid = lo + (hi - lo) / 2;",
          "    if (check(mid)) hi = mid; else lo = mid + 1;",
          "  }",
          "  return (int)lo;  // 第一個可行的 cap",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(n log(sum))`；注意 `cap` 下界要取單一最大元素、空陣列、`m=1`、值域溢位。",
          "",
          "**搭配練習重點**：容量二分、速率檢查、固定/不定長窗口、預算限制與反悔貪心。",
        ),
        7,
      ),
    },
    {
      id: 8,
      title: "7. 時間窗、並發區間與掃描線",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "時間窗與並發資源可以統一成區間問題。合併重疊按起點排序，最大並發用掃描線或差分，動態查最小可用資源用最小堆，離線查詢則按端點排序逐步加入候選。",
          "",
          "回答時要先定義端點包含性：`[s, e)` 還是 `[s, e]`，相接是否算重疊。這個細節會影響排序 tie-breaker、釋放資源的時機與答案。",
          "",
          "**效能工程視角**",
          "",
          "「最大同時並發」就是**峰值資源占用**：同時在飛的請求數決定需要多少緩衝區、多少 stream、多少記憶體高水位。掃描線／差分算峰值，最小堆做「到期即釋放」的資源回收，對應真實系統裡的連線池與記憶體池管理。",
          "",
          "[ADVANCED / NICHE] 事件排序時的 tie-break 決定語意：若「結束」與「開始」同刻，先處理結束（`[s,e)` 半開）能避免把相接區間誤算成重疊；用差分時把結束事件放在 `e`（而非 `e+1`）即等價。",
          "",
          ":::example 掃描線：最大同時並發（拆成 +1/-1 事件，按時間掃）",
          "把每個區間拆成 `{start,+1}`、`{end,-1}` 兩個事件，排序後前綴和的最大值即峰值並發；同刻先處理 -1（半開區間語意）。",
          "",
          "```cpp",
          "// 最大同時並發數（區間 [s, e)，相接不算重疊）",
          "int maxConcurrency(const vector<pair<int,int>>& intervals) {",
          "  vector<pair<int,int>> events;",
          "  events.reserve(intervals.size() * 2);",
          "  for (auto& [s, e] : intervals) {",
          "    events.push_back({s, 1});",
          "    events.push_back({e, -1});",
          "  }",
          "  // 同一時刻先處理 -1（delta 小者在前）",
          "  sort(events.begin(), events.end(), [](auto& a, auto& b) {",
          "    if (a.first != b.first) return a.first < b.first;",
          "    return a.second < b.second;",
          "  });",
          "  int cur = 0, best = 0;",
          "  for (auto& [t, delta] : events) {",
          "    cur += delta;",
          "    best = max(best, cur);",
          "  }",
          "  return best;",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(n log n)`；注意端點包含性、相接區間、空集合、同刻事件的排序 tie-break。",
          "",
          "**搭配練習重點**：區間交集、最少組數、差分容量、掃描線面積與最小區間查詢。",
        ),
        8,
      ),
    },
    {
      id: 9,
      title: "8. 資料流、日誌解析與平行歸約",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "資料流題要求只看一遍或分片處理，不能假設能保存完整歷史。先把流程拆成 map / filter / scan / reduce：每筆獨立可平行，需要前綴狀態用 scan，全域 top-k 可先分片保留候選再合併。",
          "",
          "日誌解析題要先定義欄位、空值、壞資料與時間桶策略。能邊讀邊聚合就不要二次掃描；能用 bounded heap、頻率表、滑動窗口或 sketch 就不要保存全量事件。",
          "",
          "**效能工程視角**",
          "",
          "map/filter/scan/reduce 正是**平行歸約**的骨架：獨立的 map 可分片到多核或多 lane，reduce 需要結合律（associativity）才能樹狀合併。能講「為什麼這個聚合可平行、合併順序為何不影響結果」是效能面試的關鍵；浮點加法不嚴格結合，這也是數值再現性的常見坑。",
          "",
          "[ADVANCED / NICHE] 全域 Top-K 用「分片各留 K 候選 + 合併」：每個分片維護大小為 K 的 min-heap，合併時再取全域前 K。單分片 `O(n log K)`、記憶體 `O(K)`，避免保存全量事件。",
          "",
          ":::example 串流 Top-K：大小為 K 的最小堆（堆頂是門檻）",
          "維護一個大小固定 K 的 min-heap：新元素大於堆頂才替換堆頂。堆頂即「目前第 K 大」的門檻，全程記憶體 `O(K)`。",
          "",
          "```cpp",
          "// 串流中找最大的 K 個元素，回傳由小到大",
          "vector<int> streamTopK(const vector<int>& stream, int k) {",
          "  priority_queue<int, vector<int>, greater<>> heap;  // min-heap",
          "  for (int x : stream) {",
          "    if ((int)heap.size() < k) {",
          "      heap.push(x);",
          "    } else if (x > heap.top()) {",
          "      heap.pop();",
          "      heap.push(x);  // 替換掉目前最小的候選",
          "    }",
          "  }",
          "  vector<int> res;",
          "  while (!heap.empty()) { res.push_back(heap.top()); heap.pop(); }",
          "  return res;  // 由小到大",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(n log K)` 時間、`O(K)` 空間；注意 `K > n`、重複值、空串流、壞資料列的略過策略。",
          "",
          "**搭配練習重點**：Top-K、時間桶、前綴摘要、字串流、離線查詢與 corrupted input 處理。",
        ),
        9,
      ),
    },
    {
      id: 10,
      title: "9. C++ 資源邊界與位元狀態",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "C++ 題常把限制藏在「固定容量」「不能頻繁配置」「最壞成本要穩定」「多執行緒邊界清楚」裡。設計資料結構前，先寫出容量上限、full/empty 行為、wrap-around 規則與 ownership。",
          "",
          "若狀態是一組布林且元素數小，用 bitmask 壓縮；若有累加或距離運算，用足夠寬的型別並設定不會溢位的無限大。討論同步時先問 single/multiple producer、blocking/non-blocking 與是否允許丟資料。",
          "",
          "**效能工程視角**",
          "",
          "「固定容量、不頻繁配置、最壞成本穩定」正是即時系統對**確定性延遲**的要求：熱路徑上避免 `new/delete`、用環形緩衝與物件池、把狀態壓進 bitmask 以減少 cache 行佔用。能講清楚 ownership 與 wrap-around，等於展示了寫無 GC、低抖動程式的素養。",
          "",
          "[ADVANCED / NICHE] 環形緩衝用「容量取 2 的冪 + 位元遮罩取代取模」：`idx & (cap-1)` 比 `idx % cap` 快且無分支；用 `head/tail` 計數差判斷 full/empty，避免浪費一格或額外旗標。",
          "",
          ":::example 固定容量環形緩衝（2 的冪容量、位元遮罩 wrap-around）",
          "`mask = cap-1`，索引推進用 `& mask`；`size_` 計數區分 full/empty。熱路徑無配置、無取模、行為確定。",
          "",
          "```cpp",
          "// 固定容量環形緩衝（單執行緒版；cap 須為 2 的冪）",
          "struct RingBuffer {",
          "  vector<int> buf;",
          "  int mask, head = 0, tail = 0, size_ = 0;",
          "  explicit RingBuffer(int cap) : buf(cap), mask(cap - 1) {}",
          "  bool full() const { return size_ == (int)buf.size(); }",
          "  bool empty() const { return size_ == 0; }",
          "  bool push(int x) {",
          "    if (full()) return false;  // 滿了不覆寫（依需求可改丟最舊）",
          "    buf[tail] = x;",
          "    tail = (tail + 1) & mask;  // 位元遮罩取代 % cap",
          "    size_++;",
          "    return true;",
          "  }",
          "  bool pop(int& out) {",
          "    if (empty()) return false;",
          "    out = buf[head];",
          "    head = (head + 1) & mask;",
          "    size_--;",
          "    return true;",
          "  }",
          "};",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：push/pop 皆 `O(1)` 且無配置；注意容量非 2 的冪時遮罩失效、full 時的覆寫策略、多執行緒下需改用原子索引（見第 17 章）。",
          "",
          "**搭配練習重點**：記憶體分配器、固定容量檢查、bitmask 枚舉、溢位保護與最壞複雜度。",
        ),
        10,
      ),
    },
    {
      id: 1101,
      title: "10. 服務 API、快取與索引結構",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "API 題不是算一次答案，而是設計一個物件長期支援多種操作。先列每個方法的輸入、輸出與目標複雜度，再決定 canonical state 放在哪裡，哪些 heap、set、map 或時間桶只是查詢索引。",
          "",
          "更新順序要固定：刪舊索引、改事實來源、插新索引。若用 heap lazy deletion，要說明何時判斷 stale entry；若用有序集合，要定義完整 comparator 與 tie-breaker。",
          "",
          "**效能工程視角**",
          "",
          "LRU 快取題就是**快取階層**的縮影：命中要 `O(1)`，淘汰策略決定命中率，而命中率直接換算成省下的記憶體頻寬與延遲。雜湊表 + 雙向鏈結串列的組合，對應真實快取裡「查表 + 替換鏈」的設計；能講清楚 canonical state 與索引同步，就是在講快取一致性。",
          "",
          "[ADVANCED / NICHE] LRU 用「`unordered_map<key, list::iterator>` + `list<{key,val}>`」：`splice` 把命中節點移到表頭是 `O(1)`，淘汰時從表尾刪並同步抹掉 map entry——更新順序固定為「改鏈結 → 改索引」。",
          "",
          ":::example LRU 快取：雜湊表 + 雙向鏈結串列（get/put 均 O(1)）",
          "`list` 表頭為最近使用、表尾為最久未用；map 存 key 到 list 節點的迭代器。命中用 `splice` 移到表頭，超量時淘汰表尾。",
          "",
          "```cpp",
          "// LRU 快取：get/put 均 O(1)",
          "class LRUCache {",
          "  int cap;",
          "  list<pair<int,int>> items;  // 表頭最近用，{key, value}",
          "  unordered_map<int, list<pair<int,int>>::iterator> pos;",
          " public:",
          "  explicit LRUCache(int capacity) : cap(capacity) {}",
          "  int get(int key) {",
          "    auto it = pos.find(key);",
          "    if (it == pos.end()) return -1;",
          "    items.splice(items.begin(), items, it->second);  // 移到表頭",
          "    return it->second->second;",
          "  }",
          "  void put(int key, int value) {",
          "    auto it = pos.find(key);",
          "    if (it != pos.end()) {",
          "      it->second->second = value;",
          "      items.splice(items.begin(), items, it->second);",
          "      return;",
          "    }",
          "    if ((int)items.size() == cap) {  // 淘汰表尾",
          "      pos.erase(items.back().first);",
          "      items.pop_back();",
          "    }",
          "    items.emplace_front(key, value);",
          "    pos[key] = items.begin();",
          "  }",
          "};",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：get/put 均 `O(1)`；注意 `capacity = 0`、更新既有 key、迭代器失效（`list` 的 splice 不失效）、索引與鏈結的同步順序。",
          "",
          "**搭配練習重點**：LRU、時間版本鍵值、多索引排名、任務管理、路由器與 MK average。",
        ),
        1101,
      ),
    },
    {
      id: 1102,
      title: "11. 狀態空間搜尋與壓縮 BFS",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "當「目前位置」不足以決定下一步時，就要把其他資訊放進狀態：mask、剩餘操作、階段、已取得資源或最後一次操作。只要兩條路到達同一完整狀態，後續選擇相同，就可以去重。",
          "",
          "狀態壓縮前先估數量，例如 `n * 2^n` 或 `rows * cols * masks`。若狀態數過大，要改用貪心、meet-in-the-middle、剪枝或不同建模。",
          "",
          "**效能工程視角**",
          "",
          "狀態壓縮 BFS 的記憶體上限就是 `狀態數 × 每狀態位元組`：先估數量級再決定可不可行，正是工程上「在跑之前先估記憶體與頻寬」的習慣。用整數 bitmask 當 visited key、用陣列而非 hash set，能把常數壓低並讓 visited 連續存放。",
          "",
          "[ADVANCED / NICHE] `(node, mask)` 複合狀態可編碼成單一整數 `node * (1<<k) + mask`，讓 `visited` 變成一塊 `vector<char>` 連續陣列，避免 `unordered_set` 的雜湊與 rehash 成本。",
          "",
          ":::example 狀態壓縮 BFS：訪問所有節點的最短步數（node + visited mask）",
          "狀態是 `(目前節點, 已訪問集合 mask)`；當 mask 集滿所有位元即完成。visited 用 `node*(1<<n)+mask` 索引扁平陣列。",
          "",
          "```cpp",
          "// 從任一節點出發、走遍所有節點的最短路徑長度（可重複經過）",
          "int shortestVisitingAll(const vector<vector<int>>& graph) {",
          "  int n = graph.size();",
          "  int full = (1 << n) - 1;",
          "  vector<char> seen(n * (1 << n), 0);",
          "  queue<pair<int,int>> q;  // {node, mask}",
          "  for (int i = 0; i < n; i++) {",
          "    int st = i * (1 << n) + (1 << i);",
          "    seen[st] = 1;",
          "    q.push({i, 1 << i});",
          "  }",
          "  int steps = 0;",
          "  while (!q.empty()) {",
          "    for (int sz = q.size(); sz > 0; sz--) {",
          "      auto [u, mask] = q.front();",
          "      q.pop();",
          "      if (mask == full) return steps;",
          "      for (int v : graph[u]) {",
          "        int nmask = mask | (1 << v);",
          "        int key = v * (1 << n) + nmask;",
          "        if (!seen[key]) { seen[key] = 1; q.push({v, nmask}); }",
          "      }",
          "    }",
          "    steps++;",
          "  }",
          "  return 0;",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(n^2 · 2^n)`；注意 n 上限（狀態爆炸）、單節點圖、不連通圖、visited 維度是否完整。",
          "",
          "**搭配練習重點**：造訪所有節點、key mask、推箱子、最短超級串與有序集合 BFS。",
        ),
        1102,
      ),
    },
    {
      id: 1103,
      title: "12. 多階段圖搜尋與約束",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "多階段圖搜尋通常不是一次 Dijkstra 就結束。兩個來源匯合、第二短路、時間限制、等待規則或特殊邊，都需要額外距離表或擴充狀態。",
          "",
          "常見技巧是從終點在反圖跑一次距離表，再枚舉匯合點；次短路則每點保留最短與嚴格次短；有折扣或使用次數限制時，把圖分層。",
          "",
          "**效能工程視角**",
          "",
          "分層圖（layered graph）對應「有限次特殊操作」的排程，如「最多用 k 次免費搬移」「最多切換 k 次裝置」。把 `(node, 用了幾次)` 當狀態跑最短路，就是在多階段約束下找最省延遲的執行計畫；0-1 BFS 則對應「免費邊 vs 收費邊」的零成本搬移。",
          "",
          "[ADVANCED / NICHE] 0-1 BFS 用雙端佇列取代 Dijkstra：權 0 的邊推到佇列前端、權 1 的推到後端，整體 `O(V+E)`，比 `O(E log V)` 的 Dijkstra 更快，適合大量零成本邊的場景。",
          "",
          ":::example 0-1 BFS：邊權只有 0/1（deque，前端放 0 邊、後端放 1 邊）",
          "用 `deque` 維持單調距離：遇到 0 權邊 `push_front`、1 權邊 `push_back`，第一次彈出即最短，無需堆。",
          "",
          "```cpp",
          "// 0-1 BFS：邊權僅 0 或 1 的單源最短路",
          "vector<int> zeroOneBFS(int n,",
          "    const vector<vector<pair<int,int>>>& g, int src) {",
          "  const int INF = INT_MAX;",
          "  vector<int> dist(n, INF);",
          "  deque<int> dq;",
          "  dist[src] = 0;",
          "  dq.push_front(src);",
          "  while (!dq.empty()) {",
          "    int u = dq.front();",
          "    dq.pop_front();",
          "    for (auto [v, w] : g[u]) {  // w 為 0 或 1",
          "      if (dist[u] + w < dist[v]) {",
          "        dist[v] = dist[u] + w;",
          "        if (w == 0) dq.push_front(v); else dq.push_back(v);",
          "      }",
          "    }",
          "  }",
          "  return dist;",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(V+E)`；注意非 0/1 權不能用此法、重複入隊、`INF` 比較、不可達節點。",
          "",
          "**搭配練習重點**：0-1 BFS、三次 Dijkstra、次短路、時間限制 DP 與最大邊權二分。",
        ),
        1103,
      ),
    },
    {
      id: 1104,
      title: "13. 樹分解與子樹查詢",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "層級依賴可用樹處理。基礎是：樹上一條邊會把節點分成父側與子樹側；後序 DFS 取得子樹資訊，Euler tour 把子樹映成連續區間，換根 DP 把父側資訊推給孩子。",
          "",
          "多次祖先或路徑查詢才需要 binary lifting、Euler + Fenwick 或樹鏈剖分。單次查詢通常一般 DFS 就夠。",
          "",
          "**效能工程視角**",
          "",
          "Euler tour 把子樹壓成連續區間，等於把樹狀資料**線性化成 cache 友善的陣列**——這正是把不規則指標結構轉成順序存取的通用招式，對應真實系統裡「把樹/圖攤平成扁平陣列以利向量化與預取」。",
          "",
          "[ADVANCED / NICHE] 遞迴 DFS 在深樹上會爆 stack，工程上改**顯式堆疊的迭代 DFS**；Euler tour 的 `tin/tout` 讓「子樹查詢」變成「區間查詢」，可接 Fenwick/線段樹做 `O(log n)` 更新查詢。",
          "",
          ":::example Euler tour：子樹映成連續區間 [tin, tout]（迭代 DFS）",
          "`tin[u]` 是進入時間、`tout[u]` 是離開時間；`u` 的子樹恰好是 `tin` 落在 `[tin[u], tout[u]]` 的節點，子樹查詢即區間查詢。",
          "",
          "```cpp",
          "// 迭代 DFS 計算 Euler tour 的進出時間（避免遞迴爆 stack）",
          "void eulerTour(int root, const vector<vector<int>>& g,",
          "               vector<int>& tin, vector<int>& tout) {",
          "  int n = g.size(), timer = 0;",
          "  tin.assign(n, 0);",
          "  tout.assign(n, 0);",
          "  vector<int> idx(n, 0);          // 每個節點處理到第幾個孩子",
          "  vector<int> st = {root};",
          "  tin[root] = timer++;",
          "  while (!st.empty()) {",
          "    int u = st.back();",
          "    if (idx[u] < (int)g[u].size()) {",
          "      int v = g[u][idx[u]++];",
          "      if (v == root) continue;     // 跳過回到根的邊（無父指標時）",
          "      tin[v] = timer++;",
          "      st.push_back(v);",
          "    } else {",
          "      tout[u] = timer - 1;         // 離開：子樹區間右端",
          "      st.pop_back();",
          "    }",
          "  }",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(n)` 建表、子樹查詢接 Fenwick 為 `O(log n)`；注意根的父邊處理、單節點樹、需傳父節點避免回頭、深樹改迭代。",
          "",
          "**搭配練習重點**：LCA、子樹移除、換根距離和、路徑計數與樹分割。",
        ),
        1104,
      ),
    },
    {
      id: 1105,
      title: "14. 高階 DP 與單調性優化",
      summary: withSectionPractice(
        md(
          "**觀念起點**",
          "",
          "當 DP 狀態好寫但轉移太慢時，用單調性或資料結構消掉枚舉維度。先寫出 `dp[i]` 從哪些 `j` 轉移，再看找最佳 `j` 的過程能否被取代。",
          "",
          "合法 `j` 是窗口時用單調隊列；前驅由排序決定時用二分；轉移能寫成線性函式時考慮凸包或李超線段樹。優化前要確認保留的候選集合與暴力枚舉一致。",
          "",
          "**效能工程視角**",
          "",
          "單調隊列把「每步在窗口內找最值」從 `O(k)` 降到攤還 `O(1)`，本質是用一個 deque 去掉重複比較——這跟硬體做滑動最大值（max-pool 的滑窗）是同一個演算法。能講「為什麼每個元素只進出 deque 一次」就是攤還分析的標準回答。",
          "",
          "[ADVANCED / NICHE] 單調隊列 DP：當 `dp[i] = min(dp[j]) + cost(i)`、`j ∈ [i-k, i-1]` 時，deque 從尾端彈出比新值差的舊候選、從頭端彈出過期候選，隊頭恆為窗口最佳。",
          "",
          ":::example 單調隊列 DP：窗口前驅最小值（隊頭恆為最佳 j）",
          "deque 存「候選下標」，保持其 `dp` 值單調遞增：新候選入隊前先從尾端清掉不更優的，查詢時從頭端清掉超出窗口的。",
          "",
          "```cpp",
          "// dp[i] = min(dp[j]) + a[i]，j 落在窗口 [i-k, i-1]",
          "long long windowedDP(const vector<int>& a, int k) {",
          "  int n = a.size();",
          "  vector<long long> dp(n, 0);",
          "  deque<int> dq;  // 存下標，dp 值單調遞增",
          "  for (int i = 0; i < n; i++) {",
          "    while (!dq.empty() && dq.front() < i - k) dq.pop_front();  // 過期",
          "    dp[i] = a[i];",
          "    if (!dq.empty()) dp[i] += dp[dq.front()];  // 隊頭=窗口最小 dp",
          "    while (!dq.empty() && dp[dq.back()] >= dp[i]) dq.pop_back();",
          "    dq.push_back(i);",
          "  }",
          "  return dp[n - 1];",
          "}",
          "```",
          ":::",
          "",
          "**複雜度／邊界**：`O(n)`（每元素進出 deque 各一次）；注意窗口邊界 off-by-one、空窗口、`k >= n`、相等值的 tie-break。",
          "",
          "**搭配練習重點**：單調隊列 DP、排序二分前驅、前綴最佳、狀態壓縮與高階切分。",
        ),
        1105,
      ),
    },
    {
      id: 2001,
      title: "15. [ADVANCED / NICHE] 記憶體階層、資料佈局與快取",
      summary: md(
        "**觀念起點** `[ADVANCED / NICHE]`",
        "",
        "效能工程的第一性原理是：**現代處理器算得快、等記憶體慢**。一次 L1 命中約數個週期，一次主記憶體存取上百週期。決定程式快慢的常常不是運算次數，而是**存取模式**——是否順序、是否落在同一條 cache line、是否能被預取器預測。面試裡只要題目出現「大矩陣」「大量結構走訪」「為什麼這版較慢」，背後考的就是這層。",
        "",
        "**核心概念**",
        "",
        "- **空間區域性（spatial locality）**：相鄰存取落在同一條 cache line（常 64 bytes）最划算。Row-major 陣列逐列走訪是順序存取；逐行走訪每步跨一個 row stride，幾乎每次 miss。",
        "- **AoS vs SoA**：`struct{float x,y,z;}` 的陣列（Array-of-Structs）若只用到 `x`，會把不需要的 `y,z` 一起載入、浪費頻寬且難向量化；改成 `struct{vector<float> x,y,z;}`（Struct-of-Arrays）後，對 `x` 的批次運算順序連續、可向量化。",
        "- **False sharing**：多執行緒寫入落在同一條 cache line 的不同變數，會互相使對方的 cache line 失效；用 padding/對齊把各執行緒的計數器分到不同 line。",
        "",
        ":::example 走訪順序：row-major 逐列加總（順序存取、cache 友善）",
        "同樣是加總二維陣列，**先 r 後 c**（逐列）是順序存取；把迴圈交換成先 c 後 r 會每步跨 stride、大量 cache miss——這是最常被要求解釋的效能差異。",
        "",
        "```cpp",
        "// row-major 連續走訪：外層 r、內層 c（cache 友善）",
        "long long sumRowMajor(const vector<vector<int>>& a) {",
        "  long long s = 0;",
        "  int rows = a.size(), cols = rows ? a[0].size() : 0;",
        "  for (int r = 0; r < rows; r++)",
        "    for (int c = 0; c < cols; c++)",
        "      s += a[r][c];  // 連續位址，預取器友善",
        "  return s;",
        "}",
        "```",
        ":::",
        "",
        ":::example SoA 佈局：把 x/y/z 拆成三個連續陣列（只掃 x 時不浪費頻寬）",
        "需要對單一欄位做批次運算時，SoA 讓該欄位連續存放，順序掃描且容易自動向量化。",
        "",
        "```cpp",
        "// Struct-of-Arrays：每個欄位各自連續",
        "struct Points {",
        "  vector<float> x, y, z;",
        "  // 只更新 x：順序存取、可向量化，不載入 y/z",
        "  void shiftX(float dx) {",
        "    for (size_t i = 0; i < x.size(); i++) x[i] += dx;",
        "  }",
        "};",
        "```",
        ":::",
        "",
        "**搭配練習**（用 LeetCode 題練「就地 / 連續走訪 / 佈局」直覺；標 `[ADVANCED / NICHE]` 者需額外背景）",
        "",
        "| ID | Problem | Rating | Labels |",
        "| --- | --- | --- | --- |",
        "| 48 | [原地旋轉矩陣](https://leetcode.cn/problems/rotate-image) |  | 就地、O(1) 額外空間；邊界：奇偶邊長分層 |",
        "| 54 | [螺旋矩陣](https://leetcode.cn/problems/spiral-matrix) |  | 邊界收縮；邊界：單列/單行、空矩陣 |",
        "| 73 | [矩陣置零](https://leetcode.cn/problems/set-matrix-zeroes) |  | 用首列/首欄當標記，O(1) 空間；邊界：首列本身含 0 |",
        "| 498 | [對角線遍歷](https://leetcode.cn/problems/diagonal-traverse) |  | stride 走訪、方向翻轉；邊界：非方陣 |",
        "| 304 | [二維區域和檢索](https://leetcode.cn/problems/range-sum-query-2d-immutable) |  | [ADVANCED / NICHE] 前綴和佈局，查詢 O(1)；邊界：含 0 列/欄索引 |",
        "| 329 | [矩陣中的最長遞增路徑](https://leetcode.cn/problems/longest-increasing-path-in-a-matrix) | 2042 | [ADVANCED / NICHE] 記憶化 DFS、扁平化 visited；邊界：全等值、單格 |",
      ),
    },
    {
      id: 2002,
      title: "16. [ADVANCED / NICHE] SIMD、向量化與 branchless",
      summary: md(
        "**觀念起點** `[ADVANCED / NICHE]`",
        "",
        "一條 SIMD 指令可同時對多個資料 lane（如 8 個 float）做相同運算。把迴圈寫成「無資料相依、無分支、順序存取」，編譯器就能**自動向量化**；反之，迴圈內的 `if`、提早 `break`、指標別名（aliasing）都會擋住向量化。effective performance engineering 的日常就是「移除向量化的阻礙」。",
        "",
        "**核心概念**",
        "",
        "- **Branchless**：把 `if (a<b) x=a; else x=b;` 寫成 `x = min(a,b)`，或用算術遮罩 `x = a + ((b-a) & -(a<b))`，消除分支預測失敗（mispredict 懲罰可達數十週期）。",
        "- **位元平行**：popcount、Hamming distance、子集枚舉都用整個機器字一次處理多個位元；`__builtin_popcountll` 對應硬體 popcount 指令。",
        "- **歸約的結合律**：把總和拆成多個獨立累加器再合併，能打破浮點依賴鏈、讓多 lane 並行（也要意識到浮點不嚴格結合會改變捨入結果）。",
        "",
        ":::example branchless：用算術取代分支求 min（消除分支預測失敗）",
        "在熱迴圈裡，`min/max`、條件遮罩比 `if` 更利於向量化與分支預測。",
        "",
        "```cpp",
        "// branchless min：避免不可預測分支",
        "int branchlessMin(int a, int b) {",
        "  // 當 a<b 時遮罩為全 1，否則為 0",
        "  return b + ((a - b) & -(int)(a < b));",
        "}",
        "```",
        ":::",
        "",
        ":::example 位元平行：硬體 popcount 計算 Hamming distance",
        "兩數 XOR 後數 1 的個數即位元差；`__builtin_popcountll` 走硬體指令，`O(1)`。",
        "",
        "```cpp",
        "// 兩個整數的 Hamming distance（位元差）",
        "int hammingDistance(unsigned long long a, unsigned long long b) {",
        "  return __builtin_popcountll(a ^ b);  // 硬體 popcount",
        "}",
        "```",
        ":::",
        "",
        "**搭配練習**（位元/branchless 直覺；多數需位元背景，標 `[ADVANCED / NICHE]`）",
        "",
        "| ID | Problem | Rating | Labels |",
        "| --- | --- | --- | --- |",
        "| 191 | [位元 1 的個數](https://leetcode.cn/problems/number-of-1-bits) |  | popcount、`n&(n-1)` 清最低位 1；邊界：0、全 1 |",
        "| 338 | [位元計數](https://leetcode.cn/problems/counting-bits) |  | DP `cnt[i]=cnt[i>>1]+(i&1)`；邊界：n=0 |",
        "| 461 | [漢明距離](https://leetcode.cn/problems/hamming-distance) |  | XOR + popcount，O(1)；邊界：相等為 0 |",
        "| 477 | [漢明距離總和](https://leetcode.cn/problems/total-hamming-distance) | 1652 | [ADVANCED / NICHE] 逐位統計貢獻 O(32n)；邊界：避免 O(n^2) |",
        "| 201 | [數字範圍按位與](https://leetcode.cn/problems/bitwise-and-of-numbers-range) |  | [ADVANCED / NICHE] 公共前綴；邊界：跨 2 的冪歸 0 |",
        "| 137 | [只出現一次的數字 II](https://leetcode.cn/problems/single-number-ii) |  | [ADVANCED / NICHE] 逐位模 3 / 狀態機；邊界：負數補碼 |",
        "| 260 | [只出現一次的數字 III](https://leetcode.cn/problems/single-number-iii) | 1610 | [ADVANCED / NICHE] XOR 後用最低位 1 分組；邊界：分組位選取 |",
      ),
    },
    {
      id: 2003,
      title: "17. [ADVANCED / NICHE] 多執行緒、原子操作與 lock-free",
      summary: md(
        "**觀念起點** `[ADVANCED / NICHE]`",
        "",
        "把工作攤到多核能加速，但共享狀態帶來資料競爭。面試常從「用鎖把生產者/消費者寫對」開始，深問到「為什麼這個 lock-free 佇列是正確的」「memory ordering 是什麼」。先把**同步協定（誰等誰、誰通知誰）**講清楚，再談無鎖優化。",
        "",
        "**核心概念**",
        "",
        "- **互斥與條件變數**：`mutex` 保護臨界區，`condition_variable` 讓執行緒在條件不滿足時 park、被 notify 喚醒；務必用 predicate 版 `wait` 防 spurious wakeup。",
        "- **原子與 memory ordering**：`atomic` 提供不可分割的讀改寫；`acquire/release` 建立 happens-before，`relaxed` 只保證原子性不保證順序。CAS（compare-exchange）是 lock-free 的基石。",
        "- **False sharing 與爭用**：高頻原子變數放在獨立 cache line；爭用嚴重時，分片計數（per-thread 累加再合併）常比單一原子快。",
        "",
        ":::example 有界阻塞佇列：mutex + 兩個 condition_variable（生產者/消費者）",
        "滿時生產者等 `notFull`、空時消費者等 `notEmpty`；用 predicate 版 `wait` 防偽喚醒。這是並發題的標準骨架。",
        "",
        "```cpp",
        "// 有界阻塞佇列（多生產者/多消費者安全）",
        "class BoundedBlockingQueue {",
        "  queue<int> q;",
        "  size_t cap;",
        "  mutex m;",
        "  condition_variable notFull, notEmpty;",
        " public:",
        "  explicit BoundedBlockingQueue(int capacity) : cap(capacity) {}",
        "  void enqueue(int x) {",
        "    unique_lock<mutex> lk(m);",
        "    notFull.wait(lk, [&] { return q.size() < cap; });",
        "    q.push(x);",
        "    notEmpty.notify_one();",
        "  }",
        "  int dequeue() {",
        "    unique_lock<mutex> lk(m);",
        "    notEmpty.wait(lk, [&] { return !q.empty(); });",
        "    int x = q.front();",
        "    q.pop();",
        "    notFull.notify_one();",
        "    return x;",
        "  }",
        "};",
        "```",
        ":::",
        "",
        ":::example lock-free 計數器：CAS 迴圈（relaxed/acq-rel 取捨）",
        "用 `fetch_add` 一步完成原子自增；只是計數可用 `relaxed`，若要藉它發布資料則需 `release`/`acquire` 建立順序。",
        "",
        "```cpp",
        "#include <atomic>",
        "// 純計數用 relaxed 足夠；用來『發布』資料時改 release/acquire",
        "void incr(std::atomic<long long>& counter) {",
        "  counter.fetch_add(1, std::memory_order_relaxed);",
        "}",
        "```",
        ":::",
        "",
        "**搭配練習**（LeetCode 並發專區；同步協定即背景知識，整類標 `[ADVANCED / NICHE]`）",
        "",
        "| ID | Problem | Rating | Labels |",
        "| --- | --- | --- | --- |",
        "| 1114 | [按序列印](https://leetcode.cn/problems/print-in-order) |  | [ADVANCED / NICHE] 旗標/號誌排序；邊界：notify 漏失 |",
        "| 1115 | [交替列印 FooBar](https://leetcode.cn/problems/print-foobar-alternately) |  | [ADVANCED / NICHE] 兩執行緒交握；邊界：起始順序 |",
        "| 1116 | [列印零與奇偶數](https://leetcode.cn/problems/print-zero-even-odd) |  | [ADVANCED / NICHE] 三方協調；邊界：n 邊界、結束條件 |",
        "| 1117 | [構建 H2O](https://leetcode.cn/problems/building-h2o) |  | [ADVANCED / NICHE] 號誌湊組（2:1）；邊界：barrier 重置 |",
        "| 1188 | [設計有界阻塞佇列](https://leetcode.cn/problems/design-bounded-blocking-queue) |  | [ADVANCED / NICHE] cv predicate wait；邊界：spurious wakeup |",
        "| 1226 | [哲學家進餐](https://leetcode.cn/problems/the-dining-philosophers) |  | [ADVANCED / NICHE] 死鎖避免（資源排序）；邊界：飢餓 |",
      ),
    },
    {
      id: 2004,
      title: "18. [ADVANCED / NICHE] 硬體感知 ML：roofline、矩陣分塊與算術強度",
      summary: md(
        "**觀念起點** `[ADVANCED / NICHE]`",
        "",
        "ML 核心是大量線性代數。判斷一個核心快不快，先問它是**算力受限（compute-bound）還是頻寬受限（memory-bound）**。**算術強度（arithmetic intensity）= 浮點運算數 / 搬移的位元組數**；在 roofline 模型上，強度低的核心（如逐元素加法、向量內積）撞到記憶體頻寬上限，強度高的核心（如大矩陣乘法）才可能吃滿算力。",
        "",
        "**核心概念**",
        "",
        "- **Roofline**：橫軸算術強度、縱軸可達 FLOP/s；斜線是頻寬牆、平線是算力牆，交點（knee）是兩者平衡點。優化方向就是「把點往右上推」——提高重用、減少搬移。",
        "- **矩陣乘法分塊（tiling/blocking）**：樸素 `i,j,k` 三迴圈對 cache 不友善；把矩陣切成小塊，讓每塊資料載入 cache 後被重複使用，提高算術強度——這是 BLAS、GEMM 的核心。",
        "- **資料重用與融合**：把連續算子融合（fusion）避免把中間結果寫回主記憶體再讀回，是把 memory-bound 鏈條變短的關鍵。",
        "",
        ":::example 分塊矩陣乘法：tile 提高資料重用（cache-blocked GEMM 骨架）",
        "把 i/j/k 各切成 `T` 大小的塊，內三層只在塊內運算，讓載入 cache 的小塊被重複使用，顯著減少 cache miss。",
        "",
        "```cpp",
        "// 分塊矩陣乘法 C = A * B（A: n×k, B: k×m），T 為 tile 邊長",
        "void blockedMatmul(const vector<vector<float>>& A,",
        "                   const vector<vector<float>>& B,",
        "                   vector<vector<float>>& C, int T) {",
        "  int n = A.size(), k = B.size(), m = B[0].size();",
        "  for (int ii = 0; ii < n; ii += T)",
        "    for (int kk = 0; kk < k; kk += T)",
        "      for (int jj = 0; jj < m; jj += T)",
        "        for (int i = ii; i < min(ii + T, n); i++)",
        "          for (int p = kk; p < min(kk + T, k); p++) {",
        "            float a = A[i][p];  // 提到內層外，重複用於整列",
        "            for (int j = jj; j < min(jj + T, m); j++)",
        "              C[i][j] += a * B[p][j];  // B、C 順序存取",
        "          }",
        "}",
        "```",
        ":::",
        "",
        "**搭配練習**（用矩陣/stencil/稀疏題練資料重用與走訪；標 `[ADVANCED / NICHE]` 者需硬體背景）",
        "",
        "| ID | Problem | Rating | Labels |",
        "| --- | --- | --- | --- |",
        "| 311 | [稀疏矩陣的乘法](https://leetcode.cn/problems/sparse-matrix-multiplication) | 1937 | [ADVANCED / NICHE] 跳過零元、壓縮表示；邊界：全零列 |",
        "| 1314 | [矩陣區域和](https://leetcode.cn/problems/matrix-block-sum) | 1483 | 二維前綴和、塊查詢 O(1)；邊界：邊界裁剪 |",
        "| 661 | [圖片平滑器](https://leetcode.cn/problems/image-smoother) |  | 3×3 stencil、邊界計數；邊界：角落鄰居數 |",
        "| 542 | [01 矩陣](https://leetcode.cn/problems/01-matrix) | 1786 | 多源 BFS / 兩遍 DP；邊界：無 0、全 0 |",
        "| 304 | [二維區域和檢索](https://leetcode.cn/problems/range-sum-query-2d-immutable) |  | 前綴和佈局、查詢 O(1)；邊界：索引偏移 |",
        "| 2812 | [找出最安全路徑](https://leetcode.cn/problems/find-the-safest-path-in-a-grid) | 2153 | [ADVANCED / NICHE] 多源 BFS + 二分/並查集；邊界：起終點即危險 |",
      ),
    },
    {
      id: 2005,
      title: "19. [ADVANCED / NICHE] 數值精度、量化與定點運算",
      summary: md(
        "**觀念起點** `[ADVANCED / NICHE]`",
        "",
        "低延遲推論常用較窄的數值型別（int8、fp16）換取吞吐與頻寬，代價是精度。背景知識包含：浮點為何不精確、何時溢位、如何把實數**量化**成整數再反量化、定點運算如何在無浮點單元的環境保精度。面試裡只要出現「不能用除法/浮點」「會不會溢位」「捨入往哪邊」，考的就是這層。",
        "",
        "**核心概念**",
        "",
        "- **溢位與寬型別**：中間乘積用更寬的型別（`int` 乘積放 `long long`）；比較大小用平方避免開根號；`a+b` 可能溢位時改寫 `a - (limit - b)`。",
        "- **線性量化**：`q = round(x / scale) + zero_point`，反量化 `x ≈ (q - zero_point) * scale`。重點是 scale/zero_point 的選取與飽和（clamp 到型別範圍）。",
        "- **捨入與再現性**：round-half-to-even vs round-half-up 會影響結果；浮點加法不結合，平行歸約的合併順序會改變最後幾個 bit。",
        "",
        ":::example 線性量化 / 反量化：round + clamp 到 int8（飽和處理）",
        "把 float 量化成有號 8 位元：除以 scale、加 zero_point、四捨五入後**飽和**到 [-128,127]，避免溢位回繞。",
        "",
        "```cpp",
        "#include <algorithm>",
        "#include <cmath>",
        "#include <cstdint>",
        "// 對稱/非對稱線性量化到 int8",
        "int8_t quantize(float x, float scale, int zeroPoint) {",
        "  int q = (int)std::lround(x / scale) + zeroPoint;",
        "  q = std::max(-128, std::min(127, q));  // 飽和，避免回繞",
        "  return (int8_t)q;",
        "}",
        "float dequantize(int8_t q, float scale, int zeroPoint) {",
        "  return ((int)q - zeroPoint) * scale;",
        "}",
        "```",
        ":::",
        "",
        ":::example 不用乘除做整數除法：位移逼近（溢位安全）",
        "在禁用乘除的限制下，用減去左移的被除數累加商，全程 `long long` 防溢位、單獨處理 `INT_MIN`。",
        "",
        "```cpp",
        "// 整數除法，不用 * / %（處理溢位邊界）",
        "int divide(int dividend, int divisor) {",
        "  if (dividend == INT_MIN && divisor == -1) return INT_MAX;  // 溢位",
        "  long long a = llabs((long long)dividend);",
        "  long long b = llabs((long long)divisor);",
        "  long long q = 0;",
        "  for (int s = 31; s >= 0; s--)",
        "    if ((a >> s) >= b) { a -= (b << s); q += (1LL << s); }",
        "  bool neg = (dividend < 0) ^ (divisor < 0);",
        "  return (int)(neg ? -q : q);",
        "}",
        "```",
        ":::",
        "",
        "**搭配練習**（溢位/精度/無浮點題；標 `[ADVANCED / NICHE]` 者需數值背景）",
        "",
        "| ID | Problem | Rating | Labels |",
        "| --- | --- | --- | --- |",
        "| 29 | [兩數相除](https://leetcode.cn/problems/divide-two-integers) |  | [ADVANCED / NICHE] 位移除法、溢位；邊界：INT_MIN/-1 |",
        "| 50 | [Pow(x, n)](https://leetcode.cn/problems/powx-n) |  | [ADVANCED / NICHE] 快速冪、負指數；邊界：n=INT_MIN |",
        "| 69 | [x 的平方根](https://leetcode.cn/problems/sqrtx) |  | 二分/牛頓法、整數截斷；邊界：0、1、溢位中積 |",
        "| 8 | [字串轉整數 atoi](https://leetcode.cn/problems/string-to-integer-atoi) |  | 溢位飽和、前導空白/符號；邊界：超出 int 範圍 |",
        "| 166 | [分數到小數](https://leetcode.cn/problems/fraction-to-recurring-decimal) | 1747 | [ADVANCED / NICHE] 長除法、循環節偵測；邊界：符號、溢位、整除 |",
        "| 7 | [整數反轉](https://leetcode.cn/problems/reverse-integer) |  | 反轉前判溢位；邊界：尾零、負數、越界回 0 |",
      ),
    },
    {
      id: 2006,
      title: "20. [ADVANCED / NICHE] 效能量測與 profiling 方法論",
      summary: md(
        "**觀念起點** `[ADVANCED / NICHE]`",
        "",
        "「先量測、再優化」是效能工程的紀律。面試常以系統題包裝：設計一個能持續回報 p50/p99 延遲、滑動視窗 QPS、最近 K 筆統計的計量元件。背後考的是**線上統計與資料流摘要**——在不保存全量歷史下，用 `O(1)`/`O(log n)` 維護指標。",
        "",
        "**核心概念**",
        "",
        "- **量測方法論**：分清 latency（單次耗時）與 throughput（單位時間量）；關注尾延遲（p99/p999）而非平均；Amdahl 定律提醒「只優化佔比小的熱點，整體收益有限」。",
        "- **線上統計**：running mean/variance（Welford）一遍掃完、`O(1)` 空間；滑動視窗用時間桶或雙端佇列；中位數/分位數用對頂堆動態維護。",
        "- **速率限制與時間桶**：固定視窗計數、雙端佇列存時間戳，是 QPS 監控與限流的通用結構；要定義視窗端點包含性與過期清理時機。",
        "",
        ":::example 對頂堆：資料流中位數（max-heap 存較小半、min-heap 存較大半）",
        "兩堆平衡：小於中位數的進 max-heap、其餘進 min-heap，保持大小差 <=1，堆頂組合即中位數，加入 `O(log n)`、查詢 `O(1)`。",
        "",
        "```cpp",
        "// 資料流中位數：對頂堆",
        "class MedianFinder {",
        "  priority_queue<int> lo;                            // max-heap，較小半",
        "  priority_queue<int, vector<int>, greater<>> hi;    // min-heap，較大半",
        " public:",
        "  void addNum(int num) {",
        "    lo.push(num);",
        "    hi.push(lo.top());",
        "    lo.pop();                       // 先過一手保證有序",
        "    if (hi.size() > lo.size()) {    // 再平衡大小",
        "      lo.push(hi.top());",
        "      hi.pop();",
        "    }",
        "  }",
        "  double findMedian() {",
        "    if (lo.size() > hi.size()) return lo.top();",
        "    return (lo.top() + hi.top()) / 2.0;",
        "  }",
        "};",
        "```",
        ":::",
        "",
        ":::example 滑動視窗計數：時間桶 / 雙端佇列（QPS 監控、過期清理）",
        "把事件時間戳放進 deque，查詢時從前端彈掉超出視窗的舊時間戳，佇列大小即視窗內事件數。",
        "",
        "```cpp",
        "// 最近 windowMs 毫秒內的事件數（單調時間戳）",
        "class SlidingCounter {",
        "  deque<long long> ts;",
        "  long long window;",
        " public:",
        "  explicit SlidingCounter(long long windowMs) : window(windowMs) {}",
        "  int hit(long long now) {",
        "    ts.push_back(now);",
        "    while (!ts.empty() && ts.front() <= now - window) ts.pop_front();",
        "    return (int)ts.size();",
        "  }",
        "};",
        "```",
        ":::",
        "",
        "**搭配練習**（線上統計與計量設計；標 `[ADVANCED / NICHE]` 者需資料流背景）",
        "",
        "| ID | Problem | Rating | Labels |",
        "| --- | --- | --- | --- |",
        "| 295 | [資料流的中位數](https://leetcode.cn/problems/find-median-from-data-stream) | 1919 | [ADVANCED / NICHE] 對頂堆 add O(log n)/query O(1)；邊界：偶數筆 |",
        "| 346 | [資料流中的移動平均值](https://leetcode.cn/problems/moving-average-from-data-stream) |  | 固定視窗環形和；邊界：未滿視窗 |",
        "| 362 | [敲擊計數器](https://leetcode.cn/problems/design-hit-counter) |  | 時間桶/佇列、過期清理；邊界：同刻多次、稀疏 |",
        "| 359 | [日誌速率限制器](https://leetcode.cn/problems/logger-rate-limiter) |  | 雜湊存下次可印時間；邊界：邊界時刻、首次 |",
        "| 1352 | [最後 K 個數的乘積](https://leetcode.cn/problems/product-of-the-last-k-numbers) | 1473 | [ADVANCED / NICHE] 前綴積、遇 0 重置；邊界：含 0、k 越界 |",
        "| 1146 | [快照陣列](https://leetcode.cn/problems/snapshot-array) | 1771 | [ADVANCED / NICHE] 版本鍵 + 二分；邊界：未改過的索引 |",
      ),
    },
    {
      id: 9001,
      title: "21. 題型總表（依類別）",
      summary: md(
        "下表把全部相關題目依**演算法類別**整理，方便交叉比對同一 pattern 在不同包裝下怎麼出現。先用「訊號 → 核心做法 → 代表題」鎖定方向，再依類別總表系統性掃題。標 `[ADVANCED / NICHE]` 的類別（位元/SIMD、並發、硬體感知、數值精度、量測）超出常見面試範圍，是高階效能方向的補充。",
        "",
        "**模式速查（訊號 → 做法）**",
        "",
        "| 模式 | 訊號 | 核心做法 | 代表題 |",
        "| --- | --- | --- | --- |",
        "| 圖／最短路 | 最少時間、非負權、狀態轉移 | BFS / 0-1 BFS / Dijkstra；必要時分層 | [網格中的最短路徑](https://leetcode.cn/problems/shortest-path-in-a-grid-with-obstacles-elimination)、[到達目的地的方案數](https://leetcode.cn/problems/number-of-ways-to-arrive-at-destination) |",
        "| 多源 BFS | 到最近來源的距離、距離場 | 所有來源同時入隊、距離設 0 | [地圖中的最高點](https://leetcode.cn/problems/map-of-highest-peak)、[找出最安全路徑](https://leetcode.cn/problems/find-the-safest-path-in-a-grid) |",
        "| 向量與幾何 | 相交、最近距離、投影 | 叉積、點積、掃描線或距離平方 | [圓和矩形是否有重疊](https://leetcode.cn/problems/circle-and-rectangle-overlapping)、[可見點的最大數目](https://leetcode.cn/problems/maximum-number-of-visible-points) |",
        "| 區間並發 | 最大同時數、合併窗口 | 端點排序、差分或最小堆 | [將區間分為最少組數](https://leetcode.cn/problems/divide-intervals-into-minimum-number-of-groups)、[包含每個查詢的最小區間](https://leetcode.cn/problems/minimum-interval-to-include-each-query) |",
        "| 資料流摘要 | 只能掃一遍、Top-K、時間桶 | bounded heap、hash、滑動窗口、分片歸約 | [推文計數](https://leetcode.cn/problems/tweet-counts-per-frequency)、[線上選舉](https://leetcode.cn/problems/online-election) |",
        "| 雜湊與設計 | 長期維護查詢、更新、排名、淘汰 | canonical state + 衍生索引同步 | [設計食物評分系統](https://leetcode.cn/problems/design-a-food-rating-system)、[設計路由器](https://leetcode.cn/problems/implement-router) |",
        "| C++ 資源邊界 | 固定容量、位元狀態、溢位、同步 | bounded buffer、bitmask、明確 ownership | [設計記憶體分配器](https://leetcode.cn/problems/design-memory-allocator)、[考場就座](https://leetcode.cn/problems/exam-room) |",
        "| DP 優化 | 樸素轉移過慢、窗口/排序前驅 | 單調隊列、二分、前綴最值 | [從倉庫到碼頭運輸箱子](https://leetcode.cn/problems/delivering-boxes-from-storage-to-ports)、[統計極差最大為 K 的分割方式數](https://leetcode.cn/problems/count-partitions-with-max-min-difference-at-most-k) |",
        "| 位元／SIMD `[ADVANCED / NICHE]` | popcount、branchless、逐位貢獻 | 機器字位元平行、min/max 取代分支 | [漢明距離總和](https://leetcode.cn/problems/total-hamming-distance)、[位元計數](https://leetcode.cn/problems/counting-bits) |",
        "| 並發 `[ADVANCED / NICHE]` | 多執行緒交握、生產者/消費者 | mutex + condition_variable、原子/CAS | [設計有界阻塞佇列](https://leetcode.cn/problems/design-bounded-blocking-queue)、[按序列印](https://leetcode.cn/problems/print-in-order) |",
        "| 硬體感知 `[ADVANCED / NICHE]` | 大矩陣、資料重用、稀疏 | 分塊/tiling、前綴和、跳過零元 | [稀疏矩陣的乘法](https://leetcode.cn/problems/sparse-matrix-multiplication)、[矩陣區域和](https://leetcode.cn/problems/matrix-block-sum) |",
        "| 數值精度 `[ADVANCED / NICHE]` | 不能用浮點/除法、會溢位 | 寬型別、位移、量化飽和 | [兩數相除](https://leetcode.cn/problems/divide-two-integers)、[Pow(x, n)](https://leetcode.cn/problems/powx-n) |",
        "| 量測／統計 `[ADVANCED / NICHE]` | p50/p99、滑動 QPS、最近 K | 對頂堆、時間桶、前綴積 | [資料流的中位數](https://leetcode.cn/problems/find-median-from-data-stream)、[最後 K 個數的乘積](https://leetcode.cn/problems/product-of-the-last-k-numbers) |",
        "",
        "**圖 / BFS-DFS / 樹**",
        "",
        problemTableHeader,
        categoryRows([2, 3, 5, 1102, 1103, 1104]).join("\n"),
        "",
        "**堆積 / 區間 / 資料流 / 滑動視窗**",
        "",
        problemTableHeader,
        categoryRows([7, 8, 9]).join("\n"),
        "",
        "**2D / 幾何**",
        "",
        problemTableHeader,
        categoryRows([4]).join("\n"),
        "",
        "**雜湊與設計 / C++ 資源邊界**",
        "",
        problemTableHeader,
        categoryRows([1101, 10]).join("\n"),
        "",
        "**DP / 組合**",
        "",
        problemTableHeader,
        categoryRows([6, 1105]).join("\n"),
        "",
        "小提醒：先定義資料表示與不變式，再選容器；先估狀態數與記憶體，再寫演算法；凡 `[ADVANCED / NICHE]` 題先確認自己理解背後的硬體/數值/並發背景，再談優化。",
      ),
    },
  ],
} as TutorialData.Root;
