import type { HandbookTopic } from "../model";

function md(lines: string[]): string {
  return lines.join("\n").trim();
}

export const mlPerformanceSystemDesign: HandbookTopic = {
  slug: "ml-performance-system-design",
  title: "System Design for ML Performance Engineering Interviews",
  tagline:
    "A practical framework for ML performance system design interviews: workloads, bottlenecks, GPU scheduling, profiling, optimization, and tradeoffs.",
  icon: "Gauge",
  group: "ML Performance System Design",
  // Specialized ML-infra interview track, outside the standard coding-pattern
  // frequency lists (ranked Low in content/interview-frequency.ts).
  interviewFrequency: "Low",
  sections: [
    {
      id: "interview-goal",
      title: "1. Interview Goal and Evaluation Criteria",
      body: md([
        "An ML Performance Engineer system design interview evaluates whether you can design systems where machine learning workloads, hardware behavior, distributed execution, and production constraints all matter at the same time. The goal is not to recite a generic backend architecture. The goal is to show that you can reason from requirements to workload shape, from workload shape to bottlenecks, and from bottlenecks to measurable design decisions.",
        "",
        "Interviewers usually evaluate:",
        "",
        "- **Requirement clarification**: Do you ask what is being optimized, what the service does, and what constraints are fixed?",
        "- **ML workload reasoning**: Do you distinguish model size, sequence length, batch shape, token generation, preprocessing, training, and inference behavior?",
        "- **Scalable system design**: Can you propose a service, scheduler, data path, control plane, and capacity plan that can grow without becoming unmanageable?",
        "- **Bottleneck identification**: Can you reason about compute-bound, memory-bound, queueing, communication, CPU, and storage bottlenecks?",
        "- **GPU/CPU/memory/network tradeoffs**: Do you understand when GPU utilization is high but latency is bad, or when CPU/tokenization/network prevents GPU saturation?",
        "- **Measurement and debugging**: Do you define metrics, traces, profiles, experiments, and regression detection before suggesting optimizations?",
        "- **Communication under ambiguity**: Can you state assumptions, choose a reasonable path, and summarize tradeoffs without getting lost in implementation details?",
        "",
        "A strong answer sounds like: first clarify the workload and targets, then choose a design, then explain how you would measure, find bottlenecks, and optimize. A weak answer jumps directly into boxes and arrows without defining latency, throughput, model behavior, hardware limits, or failure modes.",
      ]),
    },
    {
      id: "what-makes-it-different",
      title: "2. What Makes ML Performance System Design Different",
      body: md([
        "General backend system design often centers on request routing, databases, caching, consistency, and availability. ML performance system design still needs those ideas, but the dominant risks are different: expensive accelerators, memory bandwidth, model shape, batching behavior, queueing, and communication overhead.",
        "",
        "| Dimension | Why it matters in ML performance design |",
        "|---|---|",
        "| Throughput vs latency | Larger batches improve accelerator utilization but can increase queueing and tail latency. |",
        "| Batch size and concurrency | Effective batch size depends on model memory, sequence length, scheduler policy, and request deadlines. |",
        "| GPU utilization | High request load is not enough; kernels must keep compute units busy without being blocked by memory, CPU, or communication. |",
        "| Memory bandwidth | Many models are limited by reading weights, activations, or KV cache rather than arithmetic throughput. |",
        "| Kernel launch overhead | Small operations or fragmented execution can waste time launching many short kernels. |",
        "| Communication overhead | Training and distributed inference may be bottlenecked by collectives, parameter movement, or cross-node traffic. |",
        "| Model serving constraints | Model loading, warmup, versioning, routing, KV cache, token streaming, and request cancellation affect production behavior. |",
        "| Training vs inference | Training optimizes step time and convergence throughput; inference optimizes request latency, token latency, batching, and cost per request. |",
        "| Profiling-driven decisions | Optimizations should follow measurement; otherwise candidates tend to optimize the wrong layer. |",
        "",
        "The interviewer expects you to connect system choices to performance effects. For example, dynamic batching is not just a queueing feature; it changes accelerator occupancy, memory pressure, request fairness, and P99 latency.",
      ]),
    },
    {
      id: "recommended-framework",
      title: "3. Recommended Interview Framework",
      body: md([
        "Use the same structure every time. It keeps the answer organized and prevents premature deep dives.",
        "",
        "| Step | What to say | Questions to ask | Mistakes to avoid |",
        "|---:|---|---|---|",
        "| 1 | Clarify the problem in one sentence. | Are we designing serving, training, profiling, or scheduling? | Assuming the workload. |",
        "| 2 | Define goals and non-goals. | Optimize latency, throughput, cost, utilization, or reliability? | Trying to optimize everything equally. |",
        "| 3 | Identify workload characteristics. | Model size, sequence length, batch shape, input/output sizes? | Treating all models like the same workload. |",
        '| 4 | Define performance metrics. | P50/P95/P99, tokens/sec, cost/token, utilization, error budget? | Saying "fast" without measurable targets. |',
        "| 5 | Estimate scale. | QPS, concurrency, peak multiplier, replicas, accelerator memory? | Ignoring queueing and peak traffic. |",
        "| 6 | Propose high-level architecture. | What are the data path, control plane, scheduler, and telemetry components? | Drawing components before explaining why. |",
        "| 7 | Drill into bottlenecks. | Is the likely bottleneck compute, memory, CPU, network, scheduling, or storage? | Only discussing GPU compute. |",
        "| 8 | Discuss tradeoffs. | What changes if latency matters more than cost? | Presenting one design as universally best. |",
        "| 9 | Explain measurement plan. | What metrics, traces, profiles, and experiments validate the design? | Optimizing before measuring. |",
        "| 10 | Propose optimizations. | Which bottleneck does each optimization target? | Listing techniques without linking to symptoms. |",
        "| 11 | Discuss reliability and fallback. | What happens on overload, worker failure, model load failure, or bad rollout? | Ignoring failure modes. |",
        "| 12 | Summarize the design. | Can I restate architecture, bottlenecks, metrics, and tradeoffs in 60 seconds? | Ending abruptly after a deep dive. |",
        "",
        "A practical interview rhythm is: **clarify, quantify, architect, bottleneck, measure, optimize, trade off, summarize**.",
        "",
        "<details>",
        "<summary>Example: Interview Framework Walkthrough</summary>",
        "",
        "Suppose the prompt is: design a high-throughput inference serving system.",
        "",
        "1. Clarify whether this is online serving or offline batch inference.",
        "2. Ask for latency target, throughput target, model size, sequence length, and hardware assumptions.",
        "3. Define metrics: P95 latency, P99 latency, requests/sec, tokens/sec, time to first token, time per output token, GPU utilization, cost/token.",
        "4. Propose a gateway, request queue, batching scheduler, GPU workers, model registry, telemetry pipeline, and autoscaler.",
        "5. Deep dive into batching: max wait time, max batch size, memory-aware admission, cancellation, and priority.",
        "6. Explain bottlenecks: KV cache pressure, memory bandwidth, CPU tokenization, kernel launch overhead, and queueing.",
        "7. Explain profiling: request traces plus GPU kernel profiles plus queue metrics.",
        "8. Summarize tradeoffs: larger batches improve throughput but hurt tail latency; quantization reduces cost but may affect quality.",
        "",
        "</details>",
      ]),
    },
    {
      id: "requirement-checklist",
      title: "4. Requirement Clarification Checklist",
      body: md([
        "Start by turning an ambiguous prompt into a measurable problem. You do not need every answer before designing, but you should state assumptions when information is missing.",
        "",
        "**Workload type**",
        "",
        "- Is this for training, inference, or both?",
        "- Is it online serving, offline batch processing, streaming generation, or an internal optimization platform?",
        "- Is the workload interactive, asynchronous, or scheduled?",
        "",
        "**Performance targets**",
        "",
        "- What is the latency target: P50, P95, P99, or deadline per request?",
        "- What is the throughput target: QPS, requests/sec, tokens/sec, samples/sec, or training examples/sec?",
        "- Is time to first token important?",
        "- Is time per output token important?",
        "- What peak-to-average traffic ratio should we support?",
        "",
        "**Model and data shape**",
        "",
        "- What is the model size?",
        "- What are typical and maximum sequence lengths?",
        "- What are input and output sizes?",
        "- Are requests homogeneous or highly variable?",
        "- Is batch size fixed, dynamic, or scheduler-controlled?",
        "- What is expected concurrency?",
        "",
        "**Hardware and cost**",
        "",
        "- What accelerator type should we assume, or should the design be hardware-agnostic?",
        "- What are memory constraints per device?",
        "- Are CPU, host memory, local storage, or network constraints known?",
        "- Is cost per request or cost per token a hard target?",
        "- Can we use more devices, or must we optimize within fixed capacity?",
        "",
        "**Production constraints**",
        "",
        "- What availability target is required?",
        "- What error rate is acceptable?",
        "- Are there accuracy or quality constraints when using quantization, caching, or approximation?",
        "- Is the workload multi-tenant or single-tenant?",
        "- Are there priority classes or fairness requirements?",
        "- What observability is required: metrics, logs, traces, profiles, audit events?",
      ]),
    },
    {
      id: "core-metrics",
      title: "5. Core Metrics for ML Performance Design",
      body: md([
        "Metrics are part of the design, not an afterthought. They determine whether the system is meeting its goal and where to optimize next.",
        "",
        "| Metric | When it matters | What it reveals |",
        "|---|---|---|",
        "| P50 latency | Typical user experience or internal request path. | Median efficiency, but hides tail risk. |",
        "| P95/P99 latency | User-facing serving, multi-tenant systems, strict deadlines. | Queueing, stragglers, batching delays, overload. |",
        "| Throughput | Batch inference, training, high-volume serving. | System capacity under sustained load. |",
        "| Tokens per second | Generative inference and token streaming. | Decode performance and batching efficiency. |",
        "| Requests per second | Non-generative serving and gateway capacity. | End-to-end serving throughput. |",
        "| Time to first token | Interactive generation. | Prefill latency, queueing delay, model dispatch. |",
        "| Time per output token | Streaming decode. | Decode loop efficiency and KV cache pressure. |",
        "| GPU utilization | Accelerator cost efficiency. | Whether devices are busy, though not whether useful work is optimal. |",
        "| SM occupancy | Kernel-level compute efficiency. | Whether kernels expose enough parallel work. |",
        "| Memory bandwidth utilization | Memory-bound kernels and large models. | Whether data movement dominates compute. |",
        "| HBM usage | Large models, KV cache, training activations. | Headroom for batch size, sequence length, and model replicas. |",
        "| CPU overhead | Tokenization, scheduling, serialization, launch orchestration. | Whether host-side work starves accelerators. |",
        "| Queueing delay | Dynamic batching and overloaded services. | Difference between service time and end-to-end latency. |",
        "| Network bandwidth | Distributed training, distributed inference, remote storage. | Communication bottlenecks and cross-node saturation. |",
        "| Cost per request | Serving cost control. | Whether utilization and model choice are economically viable. |",
        "| Cost per token | Generative workloads. | Cost efficiency across prompt and decode phases. |",
        "| Error rate | Production reliability. | Failures, timeouts, overload rejection, bad model loads. |",
        "| Availability | User-facing and platform reliability. | Whether redundancy, failover, and rollout design are sufficient. |",
        "",
        "A strong interview answer ties metrics to actions. For example: if P99 is high but accelerator utilization is moderate, look at queueing, batching wait time, request shape variance, CPU overhead, and stragglers before changing kernels.",
      ]),
    },
    {
      id: "bottleneck-taxonomy",
      title: "6. Common ML Performance Bottlenecks",
      body: md([
        "Use a taxonomy so your bottleneck discussion is systematic instead of a list of guesses.",
        "",
        "| Bottleneck | Symptoms | How to measure | Common fixes | Tradeoffs |",
        "|---|---|---|---|---|",
        "| Compute-bound kernels | High compute utilization, long kernel time. | Kernel profiler, achieved FLOPs, occupancy. | Better kernels, fusion, mixed precision, compilation. | More specialized code and validation risk. |",
        "| Memory-bound kernels | High memory bandwidth, low arithmetic intensity. | Memory bandwidth counters, roofline-style analysis. | Reduce memory movement, fuse ops, improve layout, quantize. | May reduce flexibility or accuracy. |",
        "| Kernel launch overhead | Many short kernels, poor GPU utilization. | Timeline traces, launch counts, CPU-to-GPU gaps. | Fusion, graph capture, persistent kernels. | Less dynamic execution, harder debugging. |",
        "| CPU scheduling overhead | GPU idle gaps, high host CPU. | Request traces, CPU profiles, scheduler spans. | Reduce per-request work, parallelize preprocessing, cache metadata. | More control-plane complexity. |",
        "| Host-device transfer | Slow input/output movement, PCIe or interconnect saturation. | Transfer timeline, copy bandwidth counters. | Pin memory, reduce copies, overlap copies with compute. | More memory pressure. |",
        "| GPU memory fragmentation | Allocation failures despite apparent free memory. | Allocator stats, fragmentation metrics, failure logs. | Memory pools, static allocation, reuse buffers. | Less flexibility for variable shapes. |",
        "| KV cache pressure | Decode latency grows, admission failures, memory OOM. | KV bytes/request, cache hit/eviction metrics, HBM usage. | Paged KV cache, memory-aware scheduling, max context policy. | Potential request rejection or lower concurrency. |",
        "| Batch scheduling inefficiency | Low utilization or high tail latency. | Batch size distribution, queue wait, deadline misses. | Dynamic/continuous batching, bucketing, max wait tuning. | Fairness and latency complexity. |",
        "| Communication overhead | Scaling efficiency drops with more devices. | Collective time, network counters, step trace. | Overlap communication, shard differently, tune collectives. | More complex parallelism strategy. |",
        "| All-reduce/all-gather bottlenecks | Training step dominated by synchronization. | Per-collective timing and bandwidth. | Gradient bucketing, overlap, reduce precision, topology-aware placement. | Numerical and implementation risk. |",
        "| Load imbalance | Some workers idle while others lag. | Per-worker latency, queue depth, token counts, step time variance. | Better routing, work stealing, shape bucketing. | More scheduler state. |",
        "| Straggler effects | P99 much worse than median. | Trace slow requests, per-stage timing. | Hedging, timeout, partitioning, admission control. | Extra resource use. |",
        "| Queueing delay | End-to-end latency much larger than service time. | Queue wait histograms, utilization versus latency curves. | Autoscaling, backpressure, priority queues, smaller max wait. | Lower throughput or higher cost. |",
        "| Storage/data loading | Training devices wait for batches. | Data loader time, cache hit rate, storage bandwidth. | Prefetch, caching, sharding, local staging. | Storage cost and consistency complexity. |",
        "| Serialization overhead | CPU time high, large payload latency. | CPU profiles, payload size metrics. | Binary formats, zero-copy paths, payload compression where useful. | Debuggability and compatibility tradeoffs. |",
        "| Tokenization overhead | CPU bottleneck before inference. | Tokenization spans, CPU utilization, queue before GPU. | Parallel tokenization, caching, optimized tokenizer. | Cache invalidation and memory use. |",
        "",
        "In interviews, do not only name bottlenecks. Explain the symptom, the measurement, and a fix that targets that exact symptom.",
      ]),
    },
    {
      id: "architecture-patterns",
      title: "7. High-Level Architecture Patterns",
      body: md([
        "| Pattern | When to use it | Main components | Performance concerns | Failure modes |",
        "|---|---|---|---|---|",
        "| Online model serving | User-facing or synchronous internal requests. | Gateway, router, scheduler, GPU workers, model registry, telemetry. | P99 latency, batching, warmup, queueing, cost/request. | Timeouts, overload, bad model version, worker failure. |",
        "| Batch inference pipeline | Large offline jobs with relaxed latency. | Job queue, data reader, batcher, workers, output writer, retry logic. | Throughput, storage bandwidth, device utilization, checkpointing. | Partial job failure, skew, bad records, output duplication. |",
        "| Distributed training system | Large model or dataset training. | Trainer workers, coordinator, data pipeline, checkpoint store, telemetry. | Step time, collective overhead, data loading, stragglers. | Worker failure, checkpoint corruption, network partitions. |",
        "| Feature preprocessing pipeline | Transform raw inputs before serving or training. | Ingest, validation, preprocessing workers, cache, feature store or output sink. | CPU bottlenecks, serialization, cache locality. | Stale features, schema mismatch, pipeline lag. |",
        "| GPU inference scheduler | Share accelerator capacity across requests/models. | Queues, batch builder, admission controller, memory manager, dispatcher. | Batch quality, fairness, deadline misses, KV memory. | Starvation, overload, OOM, priority inversion. |",
        "| Multi-model serving | Serve many models or versions. | Model router, model cache, warm pool, eviction policy, workers. | Cold starts, memory partitioning, routing accuracy. | Model load failure, cache thrash, version mismatch. |",
        "| Model gateway/routing layer | Centralize auth, routing, quotas, and model selection. | API gateway, policy engine, router, rate limiter, fallback path. | Extra latency, routing hot spots, quota enforcement. | Wrong routing, overload, cascading failures. |",
        "| Profiling and telemetry pipeline | Continuous performance visibility. | Metrics agents, trace collectors, profile store, dashboards, alerts. | Low overhead collection, cardinality, sampling bias. | Missing data, noisy alerts, storage growth. |",
        "| Autoscaling and capacity management | Variable traffic or cost-sensitive serving. | Metrics source, scaler, warmup manager, capacity planner. | Scale-up delay, cold starts, overprovisioning. | Oscillation, insufficient capacity, slow model loading. |",
      ]),
    },
    {
      id: "inference-serving-deep-dive",
      title: "8. Deep Dive: ML Inference Serving System",
      body: md([
        "A complete inference serving answer should define the request path, the scheduler, GPU workers, memory behavior, observability, and failure handling.",
        "",
        "**Requirements**",
        "",
        "- Online model serving with a measurable latency target such as P95 and P99.",
        "- Throughput target in requests/sec or tokens/sec.",
        "- Support one or more model versions.",
        "- Preserve accuracy or quality constraints when applying quantization or approximation.",
        "- Handle overload with predictable behavior rather than unbounded queues.",
        "",
        "**APIs**",
        "",
        "- `POST /predict`: synchronous prediction for non-streaming models.",
        "- `POST /generate`: request for generative workloads; may stream tokens.",
        "- `GET /models/{model_id}/health`: model readiness and version status.",
        "- Internal scheduler API: enqueue, cancel, admit, dispatch, and report completion.",
        "",
        "**High-level architecture**",
        "",
        "- Gateway validates requests, applies quotas, and attaches priority/deadline metadata.",
        "- Router selects model version and worker pool.",
        "- Scheduler queues requests and builds batches according to latency, memory, and priority constraints.",
        "- GPU workers run model execution and stream partial results if needed.",
        "- Model manager handles loading, warmup, version pinning, and rollback.",
        "- Telemetry pipeline collects metrics, traces, logs, and selected profiles.",
        "- Autoscaler changes capacity based on queueing delay, utilization, traffic, and warmup time.",
        "",
        "<details>",
        "<summary>Diagram: Online ML Inference Serving Architecture</summary>",
        "",
        "```mermaid",
        "flowchart LR",
        "  Client[Client] --> Gateway[API Gateway]",
        "  Gateway --> Router[Model Router]",
        "  Router --> Scheduler[Batching Scheduler]",
        "  Scheduler --> WorkerA[GPU Worker Pool A]",
        "  Scheduler --> WorkerB[GPU Worker Pool B]",
        "  WorkerA --> Stream[Response Stream]",
        "  WorkerB --> Stream",
        "  Registry[Model Registry] --> WorkerA",
        "  Registry --> WorkerB",
        "  Scheduler --> Metrics[Metrics and Traces]",
        "  WorkerA --> Metrics",
        "  WorkerB --> Metrics",
        "  Metrics --> Autoscaler[Autoscaler]",
        "  Autoscaler --> Scheduler",
        "```",
        "",
        "</details>",
        "",
        "**Request lifecycle**",
        "",
        "1. Gateway validates payload size, auth metadata, priority, and deadline.",
        "2. Router selects model version and pool.",
        "3. Scheduler checks admission against queue depth, estimated memory, and deadline.",
        "4. Request waits for batching or dispatch.",
        "5. GPU worker performs preprocessing handoff, model execution, postprocessing, and response streaming.",
        "6. Telemetry records queue time, prefill/decode time, tokens/sec, memory use, and errors.",
        "",
        "**Batching and scheduling strategy**",
        "",
        "- Use dynamic batching for non-generative or fixed-shape inference.",
        "- Use continuous batching for generative workloads where requests enter and leave during decode.",
        "- Bucket by shape or sequence length when padding waste is high.",
        "- Enforce max wait time to protect P99 latency.",
        "- Apply admission control when estimated memory would exceed safe limits.",
        "",
        "**GPU worker design**",
        "",
        "- Keep model weights resident in accelerator memory.",
        "- Preallocate reusable buffers where possible.",
        "- Separate hot path inference from control-plane work.",
        "- Support cancellation for timed-out or disconnected requests.",
        "- Record per-stage timing: queue, preprocess, transfer, compute, postprocess, stream.",
        "",
        "**Memory and KV cache management**",
        "",
        "- Track memory per active request, including activations, workspace, and KV cache when relevant.",
        "- Use a memory-aware scheduler to avoid admitting batches that will OOM.",
        "- Consider paged or block-based KV cache to reduce fragmentation.",
        "- Evict or reject according to policy when cache pressure threatens the service.",
        "",
        "**Model loading and warmup**",
        "",
        "- Load model versions outside the request path.",
        "- Run warmup requests to initialize kernels, memory pools, and graph capture where applicable.",
        "- Mark workers ready only after model load, warmup, and health checks pass.",
        "",
        "**Autoscaling and cost optimization**",
        "",
        "- Scale on queueing delay, request rate, tokens/sec demand, and utilization together.",
        "- Account for model load and warmup delay in scale-up decisions.",
        "- Reduce cost through better batching, quantization when quality permits, right-sized model variants, and load balancing.",
        "",
        "**Failure handling**",
        "",
        "- Bound queues and return overload errors instead of unbounded latency.",
        "- Retry only idempotent or safe requests.",
        "- Route away from unhealthy workers.",
        "- Roll back bad model versions.",
        "- Degrade to a smaller model or lower priority path only if quality constraints allow it.",
      ]),
    },
    {
      id: "profiling-platform-deep-dive",
      title: "9. Deep Dive: Performance Profiling and Optimization System",
      body: md([
        "A profiling-driven optimization platform helps engineers answer: what changed, where did time go, which bottleneck is dominant, and did the optimization actually work?",
        "",
        "**Data collection**",
        "",
        "- Request metrics: latency breakdown, payload shape, tokens, batch size, status, deadline, model version.",
        "- Worker metrics: accelerator utilization, memory usage, CPU usage, queue depth, batch composition.",
        "- Kernel metrics: kernel duration, launch gaps, memory bandwidth, occupancy, communication time.",
        "- Distributed metrics: collective duration, network bandwidth, per-rank step time.",
        "",
        "**Metrics and traces pipeline**",
        "",
        "- Agents collect low-overhead counters continuously.",
        "- Request tracing samples end-to-end spans across gateway, scheduler, worker, and streaming response.",
        "- Kernel profiling is sampled or triggered because full profiling can be expensive.",
        "- Profiles and traces are stored with model version, hardware type, build version, and workload shape metadata.",
        "",
        "**Regression detection**",
        "",
        "- Compare current runs against baselines by model version and workload bucket.",
        "- Alert on P99 latency, queueing delay, tokens/sec drop, memory growth, error rate, or cost/token regression.",
        "- Avoid noisy alerts by requiring enough sample volume and comparing similar request shapes.",
        "",
        "**Dashboard design**",
        "",
        "- Top-level service health: availability, error rate, P95/P99, throughput, queue depth.",
        "- Accelerator view: utilization, memory, bandwidth, batch size, active requests.",
        "- Request lifecycle: queue, preprocess, transfer, compute, postprocess, stream.",
        "- Regression view: before/after by model version, hardware, request shape, and code build.",
        "",
        "<details>",
        "<summary>Example: Root-Cause Analysis Workflow</summary>",
        "",
        "A deployment causes P99 latency to increase by 40%. The profiling system helps narrow the cause:",
        "",
        "1. Dashboard shows P50 is stable but P99 is worse, suggesting tail behavior rather than average compute.",
        "2. Queueing delay increased for long-sequence requests, while short requests are stable.",
        "3. Batch size distribution changed: long requests are batched with short requests more often.",
        "4. GPU worker traces show decode steps waiting on memory allocation during high concurrency.",
        "5. Allocator stats show KV cache fragmentation increased after a scheduler change.",
        "6. Candidate fix: bucket requests by sequence length and reserve KV cache blocks before admitting requests.",
        "7. Experiment compares old scheduler, new scheduler, and bucketed scheduler on the same replay workload.",
        "",
        "The important interview point is that the platform links symptoms to evidence before proposing optimizations.",
        "",
        "</details>",
      ]),
    },
    {
      id: "gpu-scheduling-batching",
      title: "10. Deep Dive: GPU Scheduling and Batching",
      body: md([
        "GPU scheduling is where many ML performance interviews become specific. The scheduler decides which requests wait, which requests batch together, which worker runs them, and when overload is rejected.",
        "",
        "| Technique | Use case | Strength | Risk |",
        "|---|---|---|---|",
        "| Static batching | Offline inference or fixed workloads. | Simple, predictable shapes. | Poor for variable online traffic. |",
        "| Dynamic batching | Online serving with short wait budget. | Improves throughput while bounding wait. | Can hurt P99 if max wait is too high. |",
        "| Continuous batching | Token generation with variable output length. | Keeps decode loop full as requests finish. | Complex memory and fairness logic. |",
        "| Priority scheduling | Mixed criticality traffic. | Protects important requests. | Starvation without fairness controls. |",
        "| Admission control | Overload and memory pressure. | Prevents collapse and OOM. | Rejects work that might have completed. |",
        "| Backpressure | Upstream protection. | Stabilizes queues. | Requires clear client behavior. |",
        "| Memory-aware scheduling | Large contexts, KV cache, multi-model serving. | Avoids OOM and fragmentation. | May reduce utilization. |",
        "",
        "**Practical interview answer structure**",
        "",
        "1. State the objective: maximize tokens/sec or requests/sec while meeting P95/P99 deadlines.",
        "2. Define request metadata: arrival time, deadline, priority, input length, estimated output length, memory estimate.",
        "3. Describe queues: per-model, per-priority, or per-shape buckets.",
        "4. Build batches using max batch size, max tokens, max wait time, and memory budget.",
        "5. Dispatch to workers with enough memory and model readiness.",
        "6. Measure queue time, batch size distribution, deadline misses, accelerator utilization, and OOM risk.",
        "",
        "<details>",
        "<summary>Pseudocode: Memory-Aware Dynamic Batching</summary>",
        "",
        "```text",
        "while scheduler is running:",
        "  candidate_batch = []",
        "  used_memory = 0",
        "  deadline = now + max_wait",
        "",
        "  while queue is not empty and now <= deadline:",
        "    request = peek_next_request_by_priority_and_age()",
        "    estimated_memory = estimate_memory(request)",
        "",
        "    if used_memory + estimated_memory > safe_memory_budget:",
        "      break",
        "",
        "    if request.deadline < expected_finish_time(candidate_batch):",
        "      mark_deadline_risk(request)",
        "",
        "    candidate_batch.append(pop_request())",
        "    used_memory += estimated_memory",
        "",
        "    if batch_token_count(candidate_batch) >= max_tokens:",
        "      break",
        "",
        "  dispatch(candidate_batch)",
        "```",
        "",
        "</details>",
        "",
        "Tail latency control usually requires smaller max wait, shape-aware batching, priority queues, and admission control. Throughput usually improves with larger batches and more aggressive waiting. A senior answer explains where the system should sit on that curve.",
      ]),
    },
    {
      id: "distributed-training",
      title: "11. Deep Dive: Distributed Training Performance",
      body: md([
        "For distributed training, focus on system design and performance reasoning rather than training theory. The interviewer is usually looking for whether you can reason about step time, scaling efficiency, communication, memory, data loading, and fault tolerance.",
        "",
        "| Topic | Design reasoning | Performance concern |",
        "|---|---|---|",
        "| Data parallelism | Replicate model, shard data, synchronize gradients. | All-reduce cost and global batch size. |",
        "| Tensor parallelism | Split tensor computation across devices. | All-gather/reduce-scatter overhead and topology. |",
        "| Pipeline parallelism | Split layers into stages. | Bubbles, microbatching, load balance. |",
        "| ZeRO-style sharding | Shard optimizer state, gradients, and parameters. | Communication volume and memory savings. |",
        "| Gradient accumulation | Increase effective batch without immediate sync. | Longer step latency but lower sync frequency. |",
        "| Checkpointing | Save model state for recovery. | Storage bandwidth, pause time, consistency. |",
        "| Communication/computation overlap | Hide collective cost behind compute. | Requires careful bucketing and scheduling. |",
        "| All-reduce bottlenecks | Synchronization dominates step time. | Network topology, bucket size, precision. |",
        "| Data loading pipeline | Keep devices fed. | Storage, decode, augmentation, prefetch. |",
        "| Straggler mitigation | Reduce slowest-worker impact. | Skew, noisy workers, uneven batches. |",
        "| Fault tolerance | Recover from worker or node failure. | Checkpoint frequency, restart cost, partial progress. |",
        "",
        "A good training design answer often starts with the step-time equation: data loading plus forward pass plus backward pass plus optimizer plus communication plus checkpoint overhead. Then it explains which terms are likely dominant and how to measure them.",
      ]),
    },
    {
      id: "optimization-playbook",
      title: "12. Optimization Playbook",
      body: md([
        "Use this playbook only after identifying a bottleneck. In interviews, always connect the technique to the symptom it addresses.",
        "",
        "| Category | Technique | When it helps | Tradeoffs and risks |",
        "|---|---|---|---|",
        "| Compute | Kernel fusion | Many small ops or memory round trips. | Less modularity, harder debugging. |",
        "| Compute | Operator fusion | Adjacent operations can share data. | Framework/compiler limitations. |",
        "| Compute | Better kernel selection | Existing kernel underuses hardware. | More benchmarking and compatibility work. |",
        "| Compute | Mixed precision | Workload tolerates lower precision. | Numerical accuracy validation required. |",
        "| Compute | Quantization | Serving cost or memory bandwidth dominates. | Quality loss, calibration, hardware support. |",
        "| Compute | Compilation | Static or repeated graph shapes. | Compile time, dynamic shape complexity. |",
        "| Compute | Graph capture | Repeated execution graph with stable shapes. | Less flexible dynamic control flow. |",
        "| Memory | Reduce memory movement | Memory bandwidth is limiting. | May require layout or model changes. |",
        "| Memory | Improve locality | Cache misses or poor access pattern. | More specialized implementation. |",
        "| Memory | KV cache optimization | Generative decode memory is limiting. | Scheduler and cache complexity. |",
        "| Memory | Activation checkpointing | Training memory is limiting. | Extra recomputation. |",
        "| Memory | Memory pooling | Allocation overhead or fragmentation. | Larger reserved memory footprint. |",
        "| Memory | Avoid unnecessary copies | Host/device or serialization cost. | Requires ownership discipline. |",
        "| Scheduling | Dynamic batching | Online traffic with batching headroom. | Higher queueing if wait is too long. |",
        "| Scheduling | Continuous batching | Token generation with variable lengths. | Complex cancellation and fairness. |",
        "| Scheduling | Admission control | Overload or OOM risk. | Rejections must be acceptable. |",
        "| Scheduling | Priority queues | Mixed criticality requests. | Starvation risk. |",
        "| Scheduling | Load balancing | Uneven worker load. | Requires good load signals. |",
        "| Distributed | Overlap communication and computation | Collective time visible in step trace. | Harder scheduling and debugging. |",
        "| Distributed | Reduce synchronization | Frequent global barriers. | Algorithmic or convergence implications. |",
        "| Distributed | Shard model or data | Single device memory or compute insufficient. | Communication overhead. |",
        "| Distributed | Optimize collectives | Distributed scaling efficiency is poor. | Topology-specific tuning. |",
        "| System | Reduce CPU overhead | GPU idle waiting on host. | More complex asynchronous pipeline. |",
        "| System | Improve tokenization pipeline | Tokenization dominates prefill path. | Cache size and invalidation. |",
        "| System | Cache preprocessing | Repeated inputs or features. | Staleness and memory cost. |",
        "| System | Improve observability | Bottlenecks are unclear. | Metrics overhead and cardinality. |",
        "| System | Detect regressions | Performance changes across builds. | Requires stable baselines. |",
      ]),
    },
    {
      id: "tradeoff-guide",
      title: "13. Tradeoff Discussion Guide",
      body: md([
        "Interviewers expect explicit tradeoffs. Do not present every optimization as an unconditional improvement.",
        "",
        "- **Latency vs throughput**: Larger batches and longer waits improve device efficiency but increase queueing and tail latency.",
        "- **Cost vs performance**: More replicas reduce latency but increase cost; better utilization may reduce cost but complicate scheduling.",
        "- **Simplicity vs optimality**: Static batching and simple routing are easier to operate; dynamic scheduling is more efficient but harder to reason about.",
        "- **Accuracy vs speed**: Quantization, approximation, and smaller models can reduce latency and cost but require quality validation.",
        "- **Batch size vs tail latency**: Bigger batches improve throughput until padding, memory pressure, or queueing dominates.",
        "- **GPU utilization vs fairness**: A scheduler can maximize utilization by favoring large compatible batches, but smaller or low-priority requests may starve.",
        "- **Memory usage vs recomputation**: Activation checkpointing and recomputation save memory but add compute.",
        "- **Static scheduling vs dynamic scheduling**: Static plans are predictable; dynamic plans adapt to traffic and shape variance.",
        "- **Specialized kernels vs maintainability**: Custom kernels can be faster but increase testing, portability, and maintenance cost.",
        "- **Scale-up vs scale-out**: Larger devices simplify communication but may be expensive; more devices improve capacity but add network and coordination overhead.",
      ]),
    },
    {
      id: "communication",
      title: "14. How to Communicate During the Interview",
      body: md([
        "The communication goal is to sound structured, practical, and performance-aware without drowning the interviewer in low-level details too early.",
        "",
        "**Structure the answer**",
        "",
        "- Start with assumptions and goals.",
        "- Define metrics before architecture.",
        "- Draw the high-level path before deep diving.",
        "- Pick one or two likely bottlenecks and explain how you would verify them.",
        "- Summarize the design and tradeoffs at the end.",
        "",
        "**Example phrases**",
        "",
        '- "I will first clarify whether the target is latency, throughput, cost, or utilization, because the scheduler changes depending on that."',
        '- "I am assuming online inference with a P99 target; if this is offline batch inference, I would choose a more throughput-oriented design."',
        '- "Before optimizing kernels, I would separate queueing delay from service time and check whether the GPU is actually the bottleneck."',
        '- "The tradeoff is that larger batches improve tokens/sec but increase time to first token and P99 latency."',
        '- "If I get stuck, I would fall back to the request lifecycle and ask where time is spent: queue, CPU, transfer, compute, network, or postprocess."',
        "",
        "**How to avoid going too deep too early**",
        "",
        "- Do not start with kernel fusion unless the prompt asks for kernel-level optimization.",
        "- Do not design a distributed training stack if the interviewer asked for single-model online serving.",
        "- Do not spend five minutes on APIs while ignoring batch scheduling and metrics.",
        '- Ask: "Would you like me to deep dive into the scheduler, memory management, or profiling path?"',
      ]),
    },
    {
      id: "common-prompts",
      title: "15. Common Interview Prompts and How to Approach Them",
      body: md([
        "| Prompt | What to clarify | High-level design | Key bottlenecks | Metrics | Tradeoffs and deep dives |",
        "|---|---|---|---|---|---|",
        "| High-throughput ML inference serving | Online or batch, target QPS, model size, latency budget. | Gateway, router, dynamic batcher, GPU workers, autoscaler. | Batch efficiency, memory bandwidth, CPU preprocessing. | QPS, tokens/sec, P95/P99, utilization, cost/request. | Batch size vs tail latency, scheduler design. |",
        "| Low-latency model serving | Strict deadline, payload size, model variant. | Fast path gateway, small batches, warm workers, admission control. | Queueing, cold starts, CPU overhead. | P99, time to first token, error rate. | Cost vs latency, fewer larger batches. |",
        "| GPU scheduler for inference | Priorities, fairness, model count, memory constraints. | Queues, batch builder, memory admission, dispatch. | KV cache, fragmentation, starvation. | Queue wait, batch size, deadline miss rate. | Fairness vs utilization. |",
        "| Profiling system for regressions | What workloads, sampling budget, profile depth. | Metrics agents, trace collector, profile store, dashboard, alerts. | Overhead, noisy data, cardinality. | Regression delta, profile coverage, alert precision. | Sampling detail vs overhead. |",
        "| Distributed training monitoring | Parallelism strategy, scale, step target. | Worker agents, step traces, collective metrics, dashboard. | All-reduce, data loading, stragglers. | Step time, scaling efficiency, communication time. | Checkpoint cost vs recovery. |",
        "| Autoscaling GPU serving | Traffic shape, warmup time, cost target. | Scaler, warm pool, model loader, queue-based signals. | Scale-up delay, cold starts. | Queue delay, utilization, cost/token. | Overprovisioning vs latency. |",
        "| Batch inference pipeline | Data volume, SLA, output sink, retry semantics. | Job queue, readers, batchers, workers, writers. | Storage IO, skew, device utilization. | Items/sec, job completion time, failure rate. | Throughput vs freshness. |",
        "| Multi-tenant model serving | Tenant isolation, quotas, model count. | Gateway, quota manager, router, model cache, scheduler. | Cache thrash, fairness, memory partitioning. | Per-tenant P99, utilization, rejection rate. | Isolation vs efficiency. |",
        "",
        "<details>",
        "<summary>Example: Complete Mock Answer Outline</summary>",
        "",
        'For a prompt like "Design an autoscaling system for GPU model serving," a complete outline is:',
        "",
        "1. Clarify goals: P99 latency, peak QPS, model load time, cost target, and whether traffic is predictable.",
        "2. Define signals: queueing delay, request rate, tokens/sec, GPU utilization, memory headroom, error rate.",
        "3. Architecture: metrics collector, scaler controller, capacity planner, warm pool, model loader, worker readiness, rollback policy.",
        "4. Scale-up logic: forecast traffic, prewarm models, avoid routing to cold workers, account for load time.",
        "5. Scale-down logic: drain workers, preserve availability, avoid oscillation with cooldown windows.",
        "6. Bottlenecks: model loading, warmup, KV cache memory, scheduler queue, and traffic spikes.",
        "7. Tradeoffs: cost versus latency, warm spare capacity versus cold-start risk, reactive versus predictive scaling.",
        "8. Reliability: health checks, failed load handling, overload rejection, and rollback.",
        "",
        "</details>",
      ]),
    },
    {
      id: "red-flags",
      title: "16. Red Flags and Common Mistakes",
      body: md([
        "- Jumping into architecture without clarifying requirements.",
        '- Ignoring performance metrics or using vague terms like "fast" and "scalable".',
        "- Ignoring tail latency and only discussing average latency.",
        "- Treating the GPU as a black box rather than reasoning about compute, memory, launch overhead, and utilization.",
        "- Optimizing before measuring.",
        "- Not discussing bottlenecks.",
        "- Not discussing tradeoffs.",
        "- Ignoring memory constraints, especially model weights, activations, workspace, and KV cache.",
        "- Ignoring queueing effects introduced by batching.",
        "- Ignoring failure modes such as worker crash, OOM, overload, model load failure, and bad rollout.",
        "- Overfitting the design to one specific model or hardware setup.",
        "- Listing techniques like quantization or fusion without explaining when they help.",
        "- Forgetting CPU-side bottlenecks such as tokenization, serialization, scheduling, and request parsing.",
      ]),
    },
    {
      id: "final-checklist",
      title: "17. Final Interview Checklist",
      body: md([
        "Before the interview, practice reviewing this checklist quickly:",
        "",
        "- **Requirements**: training or inference, online or offline, latency, throughput, model shape, hardware, cost, availability.",
        "- **Metrics**: P50/P95/P99, tokens/sec, requests/sec, time to first token, GPU utilization, memory, queueing, cost, errors.",
        "- **Architecture**: gateway, router, scheduler, workers, model manager, telemetry, autoscaler, storage or data pipeline.",
        "- **Bottlenecks**: compute, memory, CPU, transfer, communication, scheduling, queueing, storage, serialization.",
        "- **Profiling**: request traces, kernel profiles, queue metrics, worker metrics, regression comparisons.",
        "- **Optimization**: choose techniques based on measured bottleneck.",
        "- **Tradeoffs**: latency/throughput, cost/performance, fairness/utilization, accuracy/speed, memory/recompute.",
        "- **Reliability**: health checks, bounded queues, overload behavior, rollback, retry policy, failover.",
        "- **Summary**: restate goals, architecture, bottlenecks, metrics, and tradeoffs in one minute.",
      ]),
    },
    {
      id: "collapsible-examples",
      title: "18. Collapsible Examples",
      body: md([
        "Long examples should stay collapsed so the chapter remains scannable. Use them when practicing complete interview answers.",
        "",
        "<details>",
        "<summary>Example: Designing a High-Throughput Inference System</summary>",
        "",
        "Design target: maximize sustained throughput for an online inference service while keeping P95 latency under a stated target.",
        "",
        "Architecture:",
        "",
        "1. Gateway validates requests and assigns priority/deadline.",
        "2. Router sends requests to the correct model pool.",
        "3. Scheduler performs dynamic batching with max batch size, max token budget, and max wait time.",
        "4. GPU workers keep model weights resident, reuse memory buffers, and emit request-level timing.",
        "5. Autoscaler watches queue delay, throughput, utilization, and warmup time.",
        "",
        "Main bottlenecks:",
        "",
        "- Queueing delay if batch wait is too aggressive.",
        "- Memory bandwidth if model execution is memory-bound.",
        "- CPU tokenization if accelerator has idle gaps.",
        "- KV cache pressure for generative workloads.",
        "",
        "Tradeoffs:",
        "",
        "- Larger batches lower cost per request but increase tail latency.",
        "- Quantization improves memory and throughput but requires quality validation.",
        "- More replicas reduce queueing but increase cost.",
        "",
        "</details>",
        "",
        "<details>",
        "<summary>Example: Designing a Profiling System for Regressions</summary>",
        "",
        "Design target: detect when a new model, scheduler, kernel, or deployment causes performance to regress.",
        "",
        "Data collected:",
        "",
        "- Request latency broken into queue, preprocess, transfer, compute, postprocess, stream.",
        "- Batch size, token counts, model version, worker ID, hardware type, and build version.",
        "- Accelerator utilization, memory usage, kernel timing, and communication time.",
        "",
        "Workflow:",
        "",
        "1. Establish baseline by workload bucket.",
        "2. Compare current metrics to baseline with enough sample volume.",
        "3. Alert on significant P99, tokens/sec, memory, or error-rate changes.",
        "4. Link alert to traces and sampled profiles.",
        "5. Let engineers compare experiments side by side.",
        "",
        'The platform is valuable because it turns "the model feels slower" into a measurable root-cause workflow.',
        "",
        "</details>",
      ]),
    },
    {
      id: "snippets",
      title: "19. C++ or Pseudocode Snippets",
      body: md([
        "Implementation snippets should support the system design discussion. Keep them short and practical.",
        "",
        "<details>",
        "<summary>C++17 Snippet: Simple Admission Controller</summary>",
        "",
        "```cpp",
        "// C++17 Snippet: Simple Admission Controller",
        "class AdmissionController {",
        " public:",
        "  AdmissionController(long long memory_budget_bytes, int max_queue_size)",
        "      : memory_budget_bytes_(memory_budget_bytes),",
        "        max_queue_size_(max_queue_size) {}",
        "",
        "  bool canAdmit(long long estimated_memory_bytes, int queue_size) const {",
        "    if (queue_size >= max_queue_size_) {",
        "      return false;",
        "    }",
        "    if (reserved_memory_bytes_ + estimated_memory_bytes >",
        "        memory_budget_bytes_) {",
        "      return false;",
        "    }",
        "    return true;",
        "  }",
        "",
        "  void reserve(long long estimated_memory_bytes) {",
        "    reserved_memory_bytes_ += estimated_memory_bytes;",
        "  }",
        "",
        "  void release(long long estimated_memory_bytes) {",
        "    reserved_memory_bytes_ -= estimated_memory_bytes;",
        "    if (reserved_memory_bytes_ < 0) {",
        "      reserved_memory_bytes_ = 0;",
        "    }",
        "  }",
        "",
        " private:",
        "  long long memory_budget_bytes_;",
        "  int max_queue_size_;",
        "  long long reserved_memory_bytes_ = 0;",
        "};",
        "```",
        "",
        "</details>",
        "",
        "This snippet is intentionally simple. In a real design, memory estimates would include model workspace, request shape, sequence length, output budget, and cache state.",
      ]),
    },
    {
      id: "final-summary",
      title: "20. Final Summary",
      body: md([
        "For ML Performance Engineer system design interviews, remember four ideas:",
        "",
        "- **Clarify the workload before designing**: training versus inference, online versus offline, model shape, latency, throughput, hardware, and cost.",
        "- **Design around metrics**: P95/P99, tokens/sec, requests/sec, queueing delay, utilization, memory, cost, and error rate.",
        "- **Find bottlenecks with evidence**: separate CPU, GPU compute, memory bandwidth, communication, scheduling, queueing, and storage effects.",
        "- **Optimize only after measurement**: choose batching, memory, kernel, distributed, or system optimizations based on the dominant bottleneck.",
        "",
        "The core interview strategy is: clarify, quantify, architect, bottleneck, measure, optimize, trade off, and summarize. Practice by taking one prompt, answering it in 30 minutes, then repeating the answer in a crisp five-minute version focused on metrics and bottlenecks.",
      ]),
    },
  ],
};
